from alembic import op
import sqlalchemy as sa
revision='0001_initial';down_revision=None;branch_labels=None;depends_on=None

def upgrade():
    op.create_table('users',sa.Column('id',sa.Integer,primary_key=True),sa.Column('full_name',sa.String(120),nullable=False),sa.Column('email',sa.String(160),nullable=False),sa.Column('phone',sa.String(30)),sa.Column('password_hash',sa.String(255),nullable=False),sa.Column('role',sa.String(20),nullable=False),sa.Column('is_active',sa.Boolean,nullable=False),sa.UniqueConstraint('email'))
    op.create_table('patients',sa.Column('id',sa.Integer,primary_key=True),sa.Column('user_id',sa.Integer,sa.ForeignKey('users.id',ondelete='CASCADE'),unique=True),sa.Column('date_of_birth',sa.String(20)),sa.Column('gender',sa.String(20)),sa.Column('address',sa.String(255)),sa.Column('emergency_contact',sa.String(255)))
    op.create_table('specialties',sa.Column('id',sa.Integer,primary_key=True),sa.Column('name',sa.String(120),nullable=False),sa.Column('description',sa.Text,nullable=False),sa.UniqueConstraint('name'))
    op.create_table('doctors',sa.Column('id',sa.Integer,primary_key=True),sa.Column('user_id',sa.Integer,sa.ForeignKey('users.id',ondelete='CASCADE'),unique=True),sa.Column('license_no',sa.String(80),nullable=False),sa.Column('bio',sa.Text,nullable=False),sa.Column('room',sa.String(40),nullable=False),sa.UniqueConstraint('license_no'))
    op.create_table('doctor_specialties',sa.Column('doctor_id',sa.Integer,sa.ForeignKey('doctors.id',ondelete='CASCADE'),primary_key=True),sa.Column('specialty_id',sa.Integer,sa.ForeignKey('specialties.id',ondelete='CASCADE'),primary_key=True))
    op.create_table('doctor_schedules',sa.Column('id',sa.Integer,primary_key=True),sa.Column('doctor_id',sa.Integer,sa.ForeignKey('doctors.id',ondelete='CASCADE')),sa.Column('weekday',sa.Integer,nullable=False),sa.Column('start_time',sa.String(5),nullable=False),sa.Column('end_time',sa.String(5),nullable=False),sa.Column('slot_minutes',sa.Integer,nullable=False))
    op.create_table('doctor_days_off',sa.Column('id',sa.Integer,primary_key=True),sa.Column('doctor_id',sa.Integer,sa.ForeignKey('doctors.id',ondelete='CASCADE')),sa.Column('date',sa.String(10),nullable=False),sa.Column('reason',sa.String(255),nullable=False))
    op.create_table('appointments',sa.Column('id',sa.Integer,primary_key=True),sa.Column('patient_id',sa.Integer,sa.ForeignKey('patients.id',ondelete='CASCADE')),sa.Column('doctor_id',sa.Integer,sa.ForeignKey('doctors.id')),sa.Column('appointment_date',sa.String(10),nullable=False),sa.Column('start_time',sa.String(5),nullable=False),sa.Column('end_time',sa.String(5),nullable=False),sa.Column('reason',sa.String(500),nullable=False),sa.Column('status',sa.String(20),nullable=False),sa.Column('visit_type',sa.String(20),nullable=False),sa.Column('checked_in_at',sa.DateTime(timezone=True)),sa.Column('started_at',sa.DateTime(timezone=True)),sa.Column('completed_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True)),sa.UniqueConstraint('doctor_id','appointment_date','start_time',name='uq_doctor_slot'))
    op.create_table('medical_results',sa.Column('id',sa.Integer,primary_key=True),sa.Column('appointment_id',sa.Integer,sa.ForeignKey('appointments.id',ondelete='CASCADE'),unique=True),sa.Column('diagnosis',sa.Text,nullable=False),sa.Column('notes',sa.Text,nullable=False),sa.Column('prescription',sa.Text,nullable=False))
    op.create_table('queue_entries',sa.Column('id',sa.Integer,primary_key=True),sa.Column('appointment_id',sa.Integer,sa.ForeignKey('appointments.id',ondelete='CASCADE'),unique=True),sa.Column('queue_no',sa.Integer,nullable=False),sa.Column('priority',sa.Integer,nullable=False),sa.Column('called_at',sa.DateTime(timezone=True)))
def downgrade():
    for t in ['queue_entries','medical_results','appointments','doctor_days_off','doctor_schedules','doctor_specialties','doctors','specialties','patients','users']: op.drop_table(t)
