import {useEffect,useMemo,useState} from 'react';
import {Play,CheckCircle2,PhoneCall,UserPlus,AlertTriangle,CalendarClock,Search,Clock3,UserCheck,Stethoscope,RefreshCw,ChevronRight} from 'lucide-react';
import {useAuth} from '../context/AuthContext';
import {receptionApi,doctorApi,masterApi,adminApi,paymentApi,getApiErrorMessage} from '../services/api';

const STATUS={CONFIRMED:['Đã xác nhận','confirmed'],CHECKED_IN:['Đã tiếp nhận','checked_in'],WAITING:['Đang chờ khám','waiting'],IN_PROGRESS:['Đang khám','in_progress'],COMPLETED:['Đã khám xong','completed'],CANCELLED:['Đã hủy','cancelled'],NO_SHOW:['Không đến khám','no_show']};
const statusLabel=s=>STATUS[s]?.[0]||s;
const visitLabel=v=>v==='WALK_IN'?'Khám không đặt lịch':'Đặt lịch trước';
const paymentLabel=s=>({UNPAID:'Chưa thanh toán',PENDING:'Chờ thanh toán',PAID:'Đã thanh toán',REFUND_PENDING:'Chờ hoàn tiền',REFUNDED:'Đã hoàn tiền'}[s]||'Chưa cập nhật');
const money=n=>new Intl.NumberFormat('vi-VN').format(n||0)+' ₫';
const today=()=>new Date().toISOString().slice(0,10);
const appointmentCode=id=>`AP-${String(id).padStart(6,'0')}`;

export function Reception(){
  const [date,setDate]=useState(today()),[apps,setApps]=useState([]),[queue,setQueue]=useState([]),[refunds,setRefunds]=useState([]),[q,setQ]=useState(''),[docs,setDocs]=useState([]),[selected,setSelected]=useState(null),[patientQuery,setPatientQuery]=useState(''),[patients,setPatients]=useState([]),[walk,setWalk]=useState({patient_id:'',doctor_id:'',reason:'Khám trực tiếp'}),[newPatient,setNewPatient]=useState({full_name:'',phone:'',email:'',date_of_birth:'',gender:'',address:'',emergency_contact:''}),[showNewPatient,setShowNewPatient]=useState(false),[msg,setMsg]=useState('');
  const load=()=>{setMsg('');Promise.all([receptionApi.appointments(date),receptionApi.queue(),masterApi.doctors(),receptionApi.refundRequests()]).then(([a,b,c,d])=>{setApps(a.data);setQueue(b.data);setDocs(c.data);setRefunds(d.data)}).catch(e=>setMsg(getApiErrorMessage(e,'Không tải được dữ liệu tiếp nhận')))};
  useEffect(load,[date]);
  const filtered=useMemo(()=>{const needle=q.trim().toLowerCase();if(!needle)return apps;return apps.filter(a=>[a.appointment_code,a.patient_name,a.phone,a.email,String(a.patient_id)].filter(Boolean).join(' ').toLowerCase().includes(needle))},[apps,q]);
  const act=async(fn)=>{try{await fn();load();setSelected(null)}catch(e){setMsg(getApiErrorMessage(e,'Thao tác thất bại'))}};
  const confirmRefund=async id=>{if(!confirm('Xác nhận nhân viên đã hoàn tiền cho giao dịch này?'))return;try{await paymentApi.refund(id);setMsg('Đã xác nhận hoàn tiền.');load()}catch(e){setMsg(getApiErrorMessage(e,'Không thể xác nhận hoàn tiền'))}};
  const searchPatients=async()=>{if(!patientQuery.trim()){setPatients([]);return;}try{const r=await masterApi.searchPatients(patientQuery.trim());setPatients(r.data)}catch(e){setMsg(getApiErrorMessage(e,'Không tìm thấy bệnh nhân'))}};
  const choosePatient=p=>{setWalk(x=>({...x,patient_id:String(p.id)}));setPatientQuery(`${p.full_name} · ${p.phone||p.email||''}`);setPatients([])};
  const doWalk=async()=>{try{await receptionApi.walkIn({...walk,patient_id:Number(walk.patient_id),doctor_id:Number(walk.doctor_id)});setWalk({patient_id:'',doctor_id:'',reason:'Khám trực tiếp'});setPatientQuery('');setMsg('Đã tiếp nhận lượt khám không đặt lịch và đưa vào hàng chờ.');load()}catch(e){setMsg(getApiErrorMessage(e,'Không thể tạo lượt khám'))}};
  const createPatient=async()=>{try{const r=await masterApi.createReceptionPatient(newPatient);setWalk(x=>({...x,patient_id:String(r.data.patient_id)}));setPatientQuery(`${r.data.patient_code} · ${r.data.full_name}`);setMsg(`Đã tạo hồ sơ người bệnh ${r.data.patient_code}.`);setShowNewPatient(false);setNewPatient({full_name:'',phone:'',email:'',date_of_birth:'',gender:'',address:'',emergency_contact:''});}catch(e){setMsg(getApiErrorMessage(e,'Không thể tạo hồ sơ người bệnh'))}};
  const canNoShow=a=>{const dt=new Date(`${a.date}T${a.start_time}:00`);return Date.now()-dt.getTime()>=15*60*1000};
  return <div>
    <Title title="Tiếp nhận bệnh nhân" text="Tra cứu lịch, xác nhận thông tin, tiếp nhận, xử lý không đến và tạo lượt khám trực tiếp."/>
    <div className="grid md:grid-cols-4 gap-4 mb-6"><Metric icon={CalendarClock} label="Lịch trong ngày" value={apps.length}/><Metric icon={UserCheck} label="Đã tiếp nhận" value={apps.filter(a=>['CHECKED_IN','WAITING','IN_PROGRESS','COMPLETED'].includes(a.status)).length}/><Metric icon={Clock3} label="Đang chờ" value={queue.length}/><Metric icon={AlertTriangle} label="Không đến" value={apps.filter(a=>a.status==='NO_SHOW').length}/></div>
    <div className="grid xl:grid-cols-[1.5fr_.85fr] gap-6">
      <section className="card rounded-3xl bg-white p-5">
        <div className="flex flex-col lg:flex-row lg:items-end gap-3 mb-4"><label className="w-full lg:w-48"><div className="label">Ngày làm việc</div><input className="input" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="flex-1"><div className="label">Tra cứu</div><div className="relative"><Search size={17} className="absolute left-3 top-3 text-[#90a7bb]"/><input className="input pl-10" placeholder="Mã lịch / mã bệnh nhân / họ tên / SĐT / email" value={q} onChange={e=>setQ(e.target.value)}/></div></label><button className="btn btn-soft" onClick={load}><RefreshCw size={16}/>Làm mới</button></div>
        <div className="rounded-2xl border border-[#dcecff] overflow-hidden"><div className="hidden md:grid grid-cols-[1.2fr_1.1fr_.8fr_.9fr_1.2fr] bg-[#f7fbff] px-4 py-3 text-xs font-black uppercase tracking-wider text-[#86a1b8]"><div>Lịch / Bệnh nhân</div><div>Liên hệ</div><div>Giờ</div><div>Loại lượt</div><div>Trạng thái / thao tác</div></div>
        <div className="divide-y divide-[#edf3f8]">{filtered.map(a=><div key={a.id} className="grid md:grid-cols-[1.2fr_1.1fr_.8fr_.9fr_1.2fr] gap-3 px-4 py-4 items-center"><div><div className="font-black text-[#315b83]">{a.patient_name}</div><div className="text-xs text-[#7892aa] mt-1">{a.appointment_code} · Mã BN: BN-{String(a.patient_id).padStart(6,'0')}</div></div><div className="text-sm text-[#5d7892]"><div>{a.phone||'Chưa có SĐT'}</div><div className="text-xs mt-1 text-[#8aa0b5]">{a.email}</div></div><div className="text-sm font-bold text-[#355c7e]">{a.start_time}{a.late_minutes>0&&a.status==='CONFIRMED'?<div className="text-xs text-[#b26a22] mt-1">Đến trễ khoảng {a.late_minutes} phút</div>:null}</div><div><span className="badge bg-[#f2f7fc] text-[#5f7b96]">{visitLabel(a.visit_type)}</span><div className="text-xs text-[#7d96ad] mt-2">{a.service_name||'Dịch vụ khám'}</div><div className="text-xs font-bold text-[#2f80ed] mt-1">{a.service_price?money(a.service_price):'—'}</div></div><div className="flex items-center gap-2 flex-wrap"><span className={`badge status-${a.status.toLowerCase()}`}>{statusLabel(a.status)}</span>{a.status==='CONFIRMED'&&<button className="btn btn-primary text-xs" onClick={()=>setSelected(a)}>Tiếp nhận</button>}{a.status==='CONFIRMED'&&canNoShow(a)&&<button className="btn btn-danger text-xs" onClick={()=>act(()=>receptionApi.noShow(a.id))}>Không đến</button>}<button className="btn btn-soft text-xs" onClick={()=>setSelected(a)}>Chi tiết</button></div></div>)}{!filtered.length&&<Empty text="Không tìm thấy lịch phù hợp."/>}</div></div>
      </section>
      <aside className="space-y-6">
        {selected&&<section className="card rounded-3xl bg-white p-5"><div className="flex items-center justify-between"><div className="font-extrabold text-[#234d73]">Xác nhận thông tin</div><button className="text-[#88a0b5]" onClick={()=>setSelected(null)}>×</button></div><div className="mt-4 rounded-2xl bg-[#f7fbff] p-4 space-y-3"><Info label="Mã lịch" value={appointmentCode(selected.id)}/><Info label="Mã bệnh nhân" value={`BN-${String(selected.patient_id).padStart(6,'0')}`}/><Info label="Họ tên" value={selected.patient_name}/><Info label="SĐT" value={selected.phone||'—'}/><Info label="Email" value={selected.email||'—'}/><Info label="Bác sĩ" value={`${selected.doctor_name} · Phòng ${selected.doctor_room||'—'}`}/><Info label="Thời gian" value={`${selected.start_time} · ${date}`}/><Info label="Dịch vụ" value={`${selected.service_name||'—'} · ${selected.service_price?money(selected.service_price):'—'}`}/><Info label="Thanh toán" value={`${paymentLabel(selected.payment_status)}${selected.service_price?` · ${money(selected.service_price)}`:''}`}/><Info label="Lý do khám" value={selected.reason}/></div>{selected.status==='CONFIRMED'&&<button className="btn btn-primary w-full mt-4" onClick={()=>act(()=>receptionApi.checkIn(selected.id))}><CheckCircle2 size={16}/>Xác nhận & đưa vào hàng chờ</button>}</section>}
        <section className="card rounded-3xl bg-white p-5">
          <div className="flex items-center justify-between gap-3"><div><div className="font-extrabold text-[#234d73]">Xác nhận hoàn tiền</div><div className="text-sm text-[#8199ae] mt-1">Các lịch đã hủy hoặc không đến có thanh toán đã hoàn tất.</div></div><span className="badge bg-[#fff6df] text-[#8b6200]">{refunds.length} chờ xử lý</span></div>
          <div className="mt-4 space-y-3">{refunds.map(r=><div key={r.appointment_id} className="rounded-2xl border border-[#f0e1b8] bg-[#fffaf0] p-4">
            <div className="flex items-start justify-between gap-3"><div><div className="font-black text-[#315b83]">{r.patient_name} · {r.patient_code}</div><div className="text-xs text-[#7f96aa] mt-1">{r.appointment_code} · {r.appointment_date} · {r.start_time} · {r.doctor_name}</div><div className="text-xs font-semibold text-[#8b6200] mt-1">Lý do: {r.appointment_status==='NO_SHOW'?'Không đến khám':'Hủy lịch'}</div></div><span className="badge bg-[#fff0ef] text-[#b42318]">{statusLabel(r.appointment_status)}</span></div>
            <div className="grid grid-cols-2 gap-3 mt-3"><Info label="SĐT" value={r.phone||'Chưa có SĐT'}/><Info label="Dịch vụ" value={r.service_name||'—'}/><Info label="Số tiền" value={money(r.amount)}/><Info label="Mã giao dịch" value={r.payment_reference||'—'}/><Info label="Phương thức" value={r.payment_method==='QR'?'Thanh toán QR':'Thanh toán tại cơ sở'}/><Info label="Email" value={r.email||'Chưa có email'}/></div>
            <button className="btn btn-primary w-full mt-4" onClick={()=>confirmRefund(r.appointment_id)}><CheckCircle2 size={16}/>Xác nhận đã hoàn tiền</button>
          </div>)}{!refunds.length&&<Empty text="Không có khoản hoàn tiền nào đang chờ xử lý."/>}</div>
        </section>
        <section className="card rounded-3xl bg-white p-5"><div className="flex items-center gap-2 font-extrabold text-[#234d73]"><UserPlus size={18} className="text-[#2f80ed]"/>Tiếp nhận người bệnh không đặt lịch</div><div className="text-sm text-[#8199ae] mt-1">Tra cứu theo mã người bệnh, họ tên, SĐT hoặc email. Không bắt buộc phải có SĐT.</div><div className="mt-4 flex gap-2"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-3 text-[#90a7bb]"/><input className="input pl-9" placeholder="Mã BN / họ tên / SĐT / email" value={patientQuery} onChange={e=>setPatientQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&searchPatients()}/></div><button className="btn btn-soft" onClick={searchPatients}>Tìm</button></div>{patients.length>0&&<div className="mt-2 rounded-2xl border border-[#dcecff] bg-white divide-y divide-[#edf3f8] overflow-hidden">{patients.map(p=><button key={p.id} className="w-full text-left p-3 hover:bg-[#f7fbff]" onClick={()=>choosePatient(p)}><div className="font-bold text-[#315b83]">{p.full_name}</div><div className="text-xs text-[#7892aa]">{p.patient_code} · {p.phone||'Chưa có SĐT'} · {p.email||'Chưa có email'}</div></button>)}</div>}{walk.patient_id&&<div className="mt-3 rounded-xl bg-[#edf6ff] p-3 text-sm text-[#315b83]">Đã chọn người bệnh: <b>BN-{String(walk.patient_id).padStart(6,'0')}</b> · Mã được sinh tự động</div>}<button className="btn btn-soft mt-3 w-full" onClick={()=>setShowNewPatient(true)}><UserPlus size={16}/>Thêm người bệnh mới</button><div className="space-y-3 mt-3"><select className="input" value={walk.doctor_id} onChange={e=>setWalk({...walk,doctor_id:e.target.value})}><option value="">Chọn bác sĩ</option>{docs.map(d=><option key={d.id} value={d.id}>{d.full_name} · Phòng {d.room}</option>)}</select><textarea className="input min-h-24" value={walk.reason} onChange={e=>setWalk({...walk,reason:e.target.value})} placeholder="Lý do khám"/><button disabled={!walk.patient_id||!walk.doctor_id} className="btn btn-primary w-full disabled:opacity-50" onClick={doWalk}>Tiếp nhận & vào hàng chờ</button></div></section>
      </aside>
    </div>
    {showNewPatient&&<Modal title="Thêm người bệnh mới" onClose={()=>setShowNewPatient(false)}><div className="space-y-3"><div className="rounded-xl bg-[#edf6ff] p-3 text-sm text-[#315b83]">Mã người bệnh sẽ được hệ thống sinh tự động. Không cần tự nhập mã.</div><input className="input" value={newPatient.full_name} onChange={e=>setNewPatient({...newPatient,full_name:e.target.value})} placeholder="Họ và tên *"/><div className="grid md:grid-cols-2 gap-3"><input className="input" type="date" value={newPatient.date_of_birth} onChange={e=>setNewPatient({...newPatient,date_of_birth:e.target.value})} /><select className="input" value={newPatient.gender} onChange={e=>setNewPatient({...newPatient,gender:e.target.value})}><option value="">Giới tính</option><option>Nam</option><option>Nữ</option><option>Khác</option></select></div><input className="input" value={newPatient.phone} onChange={e=>setNewPatient({...newPatient,phone:e.target.value})} placeholder="Số điện thoại (không bắt buộc)"/><input className="input" value={newPatient.email} onChange={e=>setNewPatient({...newPatient,email:e.target.value})} placeholder="Email (không bắt buộc)"/><textarea className="input min-h-20" value={newPatient.address} onChange={e=>setNewPatient({...newPatient,address:e.target.value})} placeholder="Địa chỉ (không bắt buộc)"/><textarea className="input min-h-20" value={newPatient.emergency_contact} onChange={e=>setNewPatient({...newPatient,emergency_contact:e.target.value})} placeholder="Người liên hệ khẩn cấp (không bắt buộc)"/><button disabled={!newPatient.full_name.trim()} className="btn btn-primary w-full disabled:opacity-50" onClick={createPatient}>Tạo hồ sơ & sinh mã người bệnh</button></div></Modal>}
    {msg&&<div className="mt-5 rounded-2xl bg-[#edf6ff] p-3 text-sm text-[#2f6aa3]">{msg}</div>}
  </div>
}

export function Queue(){
  const [queue,setQueue]=useState([]),[docs,setDocs]=useState([]),[doc,setDoc]=useState(''),[msg,setMsg]=useState('');
  const load=()=>Promise.all([receptionApi.queue(doc||undefined),masterApi.doctors()]).then(([q,d])=>{setQueue(q.data);setDocs(d.data)}).catch(e=>setMsg(getApiErrorMessage(e,'Không tải được hàng chờ')));
  useEffect(load,[doc]); const call=async id=>{try{await receptionApi.call(id);setMsg('Đã gọi bệnh nhân tiếp theo.');load()}catch(e){setMsg(getApiErrorMessage(e,'Không thể gọi'))}};
  return <div><Title title="Hàng chờ khám" text="Theo dõi thứ tự ưu tiên và gọi bệnh nhân tiếp theo."/><div className="card rounded-3xl bg-white p-5"><div className="flex flex-col md:flex-row md:items-end gap-3"><label className="w-full md:w-80"><div className="label">Lọc theo bác sĩ</div><select className="input" value={doc} onChange={e=>setDoc(e.target.value)}><option value="">Tất cả bác sĩ</option>{docs.map(d=><option key={d.id} value={d.id}>{d.full_name} · Phòng {d.room}</option>)}</select></label><div className="text-sm text-[#7892aa]">Ưu tiên: lịch đúng giờ → bệnh nhân đến trễ → khám không đặt lịch.</div></div><div className="mt-5 space-y-3">{queue.map((q,i)=><div key={q.id} className="rounded-2xl border border-[#dcecff] bg-[#fbfdff] p-4 flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div className="flex items-start gap-4"><div className="h-12 w-12 rounded-2xl bg-[#eaf4ff] text-[#2f80ed] grid place-items-center font-black text-lg">{q.queue_no}</div><div><div className="font-black text-[#2f5578]">{q.patient_name}</div><div className="text-sm text-[#7a94ab] mt-1">{q.patient_phone||'Chưa có SĐT'} · {q.doctor_name}</div><div className="text-xs text-[#8aa0b5] mt-1">{appointmentCode(q.appointment_id)} · {visitLabel(q.visit_type)} · {q.start_time}</div></div></div><div className="flex items-center gap-2 flex-wrap"><span className={`badge status-${q.status.toLowerCase()}`}>{statusLabel(q.status)}</span>{q.called_at?<span className="badge bg-[#eaf8ef] text-[#16733b]">Đã gọi</span>:<span className="badge bg-[#fff7d9] text-[#896a00]">Chưa gọi</span>}<button className="btn btn-primary" onClick={()=>call(q.id)}><PhoneCall size={16}/>Gọi bệnh nhân</button></div></div>)}{!queue.length&&<Empty text="Hiện chưa có bệnh nhân trong hàng chờ."/>}</div>{msg&&<div className="mt-4 rounded-xl bg-[#edf6ff] text-[#2f6aa3] p-3 text-sm">{msg}</div>}</div></div>
}

export function DoctorHome(){
  const {user}=useAuth(); const [queue,setQueue]=useState([]),[apps,setApps]=useState([]),[selected,setSelected]=useState(null),[tab,setTab]=useState('today'),[form,setForm]=useState({diagnosis:'',notes:'',prescription:''}),[msg,setMsg]=useState('');
  const id=user?.doctor_id; const load=()=>{if(!id)return;Promise.all([doctorApi.mine(),doctorApi.queue(id)]).then(([a,q])=>{setApps(a.data);setQueue(q.data)}).catch(e=>setMsg(getApiErrorMessage(e,'Không tải được dữ liệu khám')))};
  useEffect(load,[id]); const todayApps=apps.filter(a=>a.date===today() && ['WAITING','IN_PROGRESS','COMPLETED'].includes(a.status)); const current=tab==='today'?todayApps:apps;
  const start=async a=>{try{await doctorApi.start(a.id);setMsg(`Đã bắt đầu khám ${a.patient_name}.`);load()}catch(e){setMsg(getApiErrorMessage(e,'Không thể bắt đầu khám'))}};
  const finish=async a=>{try{await doctorApi.result(a.id,form);await doctorApi.complete(a.id);setMsg('Đã lưu kết quả và hoàn thành lượt khám.');setSelected(null);setForm({diagnosis:'',notes:'',prescription:''});load()}catch(e){setMsg(getApiErrorMessage(e,'Không thể hoàn thành lượt khám'))}};
  return <div><Title title="Khám bệnh" text="Tiếp nhận bệnh nhân trong hàng chờ, bắt đầu khám, ghi kết quả và hoàn thành lượt khám."/><div className="grid md:grid-cols-3 gap-4 mb-6"><Metric icon={Clock3} label="Đang chờ" value={queue.length}/><Metric icon={Stethoscope} label="Đang khám" value={apps.filter(a=>a.status==='IN_PROGRESS'&&a.date===today()).length}/><Metric icon={CheckCircle2} label="Đã hoàn thành hôm nay" value={apps.filter(a=>a.status==='COMPLETED'&&a.date===today()).length}/></div><div className="flex gap-2 mb-4"><button className={`btn ${tab==='today'?'btn-primary':'btn-soft'}`} onClick={()=>setTab('today')}>Lịch hôm nay</button><button className={`btn ${tab==='history'?'btn-primary':'btn-soft'}`} onClick={()=>setTab('history')}>Lịch sử</button></div><div className="space-y-3">{current.map(a=><div key={a.id} className="card rounded-2xl bg-white p-5"><div className="flex flex-col lg:flex-row justify-between gap-4"><div><div className="flex items-center gap-2"><div className="font-black text-[#2b5478] text-lg">{a.patient_name}</div><span className="badge bg-[#f2f7fc] text-[#617e99]">{visitLabel(a.visit_type)}</span></div><div className="text-sm text-[#7d96ab] mt-1">{appointmentCode(a.id)} · {a.date} · {a.start_time} · {a.phone||'Chưa có SĐT'}</div><div className="text-sm text-[#6a849b] mt-1">Lý do: {a.reason}</div>{a.called_at&&<div className="mt-2 text-xs font-bold text-[#16733b]">Bệnh nhân đã được gọi</div>}</div><div className="flex items-center gap-2 flex-wrap"><span className={`badge status-${a.status.toLowerCase()}`}>{statusLabel(a.status)}</span>{a.status==='WAITING'&&<button className="btn btn-primary text-sm" onClick={()=>start(a)}><Play size={15}/>Bắt đầu khám</button>}{a.status==='IN_PROGRESS'&&<button className="btn btn-soft text-sm" onClick={()=>{setSelected(a);setForm({diagnosis:a.diagnosis||'',notes:a.notes||'',prescription:a.prescription||''})}}>Nhập kết quả</button>}</div></div>{selected?.id===a.id&&<div className="mt-4 pt-4 border-t border-[#e4eff8]"><div className="grid md:grid-cols-2 gap-3"><textarea className="input min-h-24" placeholder="Chẩn đoán" value={form.diagnosis} onChange={e=>setForm({...form,diagnosis:e.target.value})}/><textarea className="input min-h-24" placeholder="Ghi chú" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><textarea className="input min-h-24 md:col-span-2" placeholder="Đơn thuốc / hướng dẫn" value={form.prescription} onChange={e=>setForm({...form,prescription:e.target.value})}/></div><div className="flex gap-2 mt-3"><button className="btn btn-primary" onClick={()=>finish(a)}><CheckCircle2 size={16}/>Lưu & hoàn thành</button><button className="btn btn-outline" onClick={()=>setSelected(null)}>Đóng</button></div></div>}</div>)}{!current.length&&<Empty text="Chưa có lượt khám phù hợp."/>}</div>{msg&&<div className="mt-5 rounded-xl bg-[#edf6ff] text-[#2f6aa3] p-3 text-sm">{msg}</div>}</div>
}

export function DoctorSchedule(){
  const {user}=useAuth(); const id=user?.doctor_id; const [rows,setRows]=useState([]),[days,setDays]=useState([]),[s,setS]=useState({weekday:0,start_time:'08:00',end_time:'17:00',slot_minutes:30}),[off,setOff]=useState({date:'',reason:'Ngày nghỉ'}),[msg,setMsg]=useState('');
  const load=()=>{if(id)Promise.all([doctorApi.schedules(id),doctorApi.daysOff(id)]).then(([a,b])=>{setRows(a.data);setDays(b.data)}).catch(e=>setMsg(getApiErrorMessage(e,'Không tải được lịch làm việc')))}; useEffect(load,[id]);
  const addSchedule=async()=>{try{await doctorApi.addSchedule(id,s);setMsg('Đã lưu ca làm việc.');load()}catch(e){setMsg(getApiErrorMessage(e,'Không thể lưu ca làm việc'))}};
  const addDayOff=async()=>{try{await doctorApi.addDayOff(id,off);setOff({date:'',reason:'Ngày nghỉ'});setMsg('Đã thêm ngày nghỉ.');load()}catch(e){setMsg(getApiErrorMessage(e,'Không thể thêm ngày nghỉ'))}};
  return <div><Title title="Lịch làm việc" text="Quản lý ca làm việc và ngày nghỉ. Booking chỉ hiển thị slot theo lịch bác sĩ."/><div className="grid xl:grid-cols-2 gap-6"><section className="card rounded-3xl bg-white p-6"><div className="font-extrabold text-[#234d73]">Ca làm việc</div><div className="grid md:grid-cols-3 gap-3 mt-4"><select className="input" value={s.weekday} onChange={e=>setS({...s,weekday:Number(e.target.value)})}>{['Thứ 2','Thứ 3','Thứ 4','Thứ 5','Thứ 6','Thứ 7','Chủ nhật'].map((x,i)=><option key={i} value={i}>{x}</option>)}</select><input className="input" type="time" value={s.start_time} onChange={e=>setS({...s,start_time:e.target.value})}/><input className="input" type="time" value={s.end_time} onChange={e=>setS({...s,end_time:e.target.value})}/></div><div className="mt-3 text-xs text-[#8aa1b5]">Mỗi slot {s.slot_minutes} phút.</div><button disabled={!id} onClick={addSchedule} className="btn btn-primary mt-4">Lưu ca làm việc</button><div className="mt-6 space-y-2">{rows.map(x=><div key={x.id} className="rounded-xl bg-[#f7fbff] p-3 text-sm font-semibold text-[#52728f]">{['Thứ 2','Thứ 3','Thứ 4','Thứ 5','Thứ 6','Thứ 7','Chủ nhật'][x.weekday]} · {x.start_time}-{x.end_time} · {x.slot_minutes} phút</div>)}{!rows.length&&<div className="text-sm text-[#8199ae]">Chưa có ca làm việc.</div>}</div></section><section className="card rounded-3xl bg-white p-6"><div className="font-extrabold text-[#234d73]">Ngày nghỉ</div><div className="grid md:grid-cols-[1fr_1.5fr] gap-3 mt-4"><input className="input" type="date" value={off.date} onChange={e=>setOff({...off,date:e.target.value})}/><input className="input" value={off.reason} onChange={e=>setOff({...off,reason:e.target.value})} placeholder="Lý do nghỉ"/></div><button disabled={!id||!off.date} onClick={addDayOff} className="btn btn-primary mt-4">Thêm ngày nghỉ</button><div className="mt-6 space-y-2">{days.map(x=><div key={x.id} className="rounded-xl bg-[#fff7f2] border border-[#f5e1d1] p-3 text-sm text-[#7c604a]">{x.date} · {x.reason||'Ngày nghỉ'}</div>)}{!days.length&&<div className="text-sm text-[#8199ae]">Chưa có ngày nghỉ được khai báo.</div>}</div></section></div>{msg&&<div className="mt-5 rounded-xl bg-[#edf6ff] text-[#2f6aa3] p-3 text-sm">{msg}</div>}</div>
}

export function Admin(){
  const [tab,setTab]=useState('overview'),[d,setD]=useState(null),[err,setErr]=useState(''),[msg,setMsg]=useState('');
  const [patients,setPatients]=useState([]),[patientQ,setPatientQ]=useState(''),[editingPatient,setEditingPatient]=useState(null);
  const [doctors,setDoctors]=useState([]),[specialties,setSpecialties]=useState([]),[editingDoctor,setEditingDoctor]=useState(null),[showDoctorForm,setShowDoctorForm]=useState(false),[showSpecialtyForm,setShowSpecialtyForm]=useState(false);
  const [users,setUsers]=useState([]),[userQ,setUserQ]=useState(''),[userGroup,setUserGroup]=useState('staff'),[editingUser,setEditingUser]=useState(null),[resetUser,setResetUser]=useState(null),[resetPassword,setResetPassword]=useState('');
  const [specialtyForm,setSpecialtyForm]=useState({name:'',description:''});
  const [doctorForm,setDoctorForm]=useState({full_name:'',email:'',phone:'',password:'123456',license_no:'',bio:'',room:'101',specialty_id:''});
  const [services,setServices]=useState([]),[editingService,setEditingService]=useState(null),[showServiceForm,setShowServiceForm]=useState(false),[serviceForm,setServiceForm]=useState({specialty_id:'',code:'',name:'',description:'',price:0,active:true});
  const [appointments,setAppointments]=useState([]),[appointmentDate,setAppointmentDate]=useState(today()),[rescheduling,setRescheduling]=useState(null),[rescheduleSlots,setRescheduleSlots]=useState([]);
  const SHIFT_PRESETS=[
    {key:'office',name:'Ca hành chính',time:'08:00 - 17:00',start_time:'08:00',end_time:'17:00',slot_minutes:30},
    {key:'shift1',name:'Ca 1 - Buổi sáng',time:'07:00 - 11:30',start_time:'07:00',end_time:'11:30',slot_minutes:30},
    {key:'shift2',name:'Ca 2 - Buổi chiều',time:'13:00 - 17:00',start_time:'13:00',end_time:'17:00',slot_minutes:30},
    {key:'evening',name:'Ca tối',time:'17:00 - 21:00',start_time:'17:00',end_time:'21:00',slot_minutes:30},
    {key:'oncall',name:'Ca trực',time:'21:00 - 23:00',start_time:'21:00',end_time:'23:00',slot_minutes:30},
  ];
  const [scheduleDoctors,setScheduleDoctors]=useState([]),[scheduleDoctorId,setScheduleDoctorId]=useState(''),[scheduleRows,setScheduleRows]=useState([]),[scheduleDaysOff,setScheduleDaysOff]=useState([]),[scheduleForm,setScheduleForm]=useState({weekday:0,start_time:'08:00',end_time:'17:00',slot_minutes:30}),[dayOffForm,setDayOffForm]=useState({date:'',reason:'Ngày nghỉ'}),[selectedShift,setSelectedShift]=useState('office');
  const loadDash=()=>adminApi.dashboard().then(r=>setD(r.data)).catch(e=>setErr(getApiErrorMessage(e,'Không tải được dashboard')));
  useEffect(()=>{loadDash();masterApi.specialties().then(r=>setSpecialties(r.data)).catch(()=>{});},[]);
  useEffect(()=>{if(tab==='patients') adminApi.patients(patientQ).then(r=>setPatients(r.data)).catch(e=>setErr(getApiErrorMessage(e,'Không tải được bệnh nhân')));},[tab]);
  const loadUsers=async()=>{try{setErr('');const r=await adminApi.accounts(userQ.trim(),userGroup);setUsers(Array.isArray(r.data)?r.data:[]);}catch(e){setUsers([]);setErr(getApiErrorMessage(e,'Không tải được tài khoản'));}};
  useEffect(()=>{if(tab==='users') loadUsers();},[tab,userGroup,userQ]);
  useEffect(()=>{if(tab==='doctors'){adminApi.doctors().then(r=>setDoctors(r.data)).catch(e=>setErr(getApiErrorMessage(e,'Không tải được bác sĩ')))}} ,[tab]);
  useEffect(()=>{if(tab==='specialties'){adminApi.specialties().then(r=>setSpecialties(r.data)).catch(e=>setErr(getApiErrorMessage(e,'Không tải được chuyên khoa')))}},[tab]);
  useEffect(()=>{if(tab==='services'){adminApi.services().then(r=>setServices(r.data)).catch(e=>setErr(getApiErrorMessage(e,'Không tải được dịch vụ')))}} ,[tab]);
  useEffect(()=>{if(tab==='appointments'){receptionApi.appointments(appointmentDate).then(r=>setAppointments(r.data)).catch(e=>setErr(getApiErrorMessage(e,'Không tải được lịch khám')))}},[tab,appointmentDate]);
  useEffect(()=>{if(rescheduling){bookingApi.slots(rescheduling.doctor_id,rescheduling.date).then(r=>setRescheduleSlots(r.data)).catch(()=>setRescheduleSlots([]))}else setRescheduleSlots([])},[rescheduling?.doctor_id,rescheduling?.date]);
  useEffect(()=>{if(tab==='schedules') adminApi.doctors().then(r=>{setScheduleDoctors(r.data);if(!scheduleDoctorId&&r.data[0])setScheduleDoctorId(String(r.data[0].doctor_id))}).catch(e=>setErr(getApiErrorMessage(e,'Không tải được bác sĩ')))},[tab]);
  useEffect(()=>{if(tab==='schedules'&&scheduleDoctorId) Promise.all([doctorApi.schedules(Number(scheduleDoctorId)),doctorApi.daysOff(Number(scheduleDoctorId))]).then(([a,b])=>{setScheduleRows(a.data);setScheduleDaysOff(b.data)}).catch(e=>setErr(getApiErrorMessage(e,'Không tải được lịch làm việc')))},[tab,scheduleDoctorId]);
  const flash=x=>{setMsg(x);setErr('');setTimeout(()=>setMsg(''),2500)};
  const savePatient=async()=>{try{await adminApi.updatePatient(editingPatient.patient_id,editingPatient);setEditingPatient(null);flash('Đã cập nhật thông tin bệnh nhân');adminApi.patients(patientQ).then(r=>setPatients(r.data));}catch(e){setErr(getApiErrorMessage(e,'Không thể cập nhật bệnh nhân'))}};
  const saveSpecialty=async()=>{try{const r=await adminApi.createSpecialty({name:specialtyForm.name.trim(),description:specialtyForm.description.trim()});setSpecialties(prev=>[...prev,r.data]);setSpecialtyForm({name:'',description:''});setShowSpecialtyForm(false);flash('Đã thêm chuyên khoa. Hệ thống đã cập nhật danh mục.')}catch(e){setErr(getApiErrorMessage(e,'Không thể thêm chuyên khoa'))}};
  const saveNewDoctor=async()=>{try{if(!doctorForm.specialty_id)throw new Error('Vui lòng chọn chuyên khoa');const r=await adminApi.createDoctor({...doctorForm,specialty_id:Number(doctorForm.specialty_id)});setShowDoctorForm(false);setDoctorForm({full_name:'',email:'',phone:'',password:'123456',license_no:'',bio:'',room:'101',specialty_id:''});flash(`Đã thêm bác sĩ ${r.data.full_name}. Tài khoản đã được tạo. Bây giờ có thể cấu hình lịch làm việc.`);const [dr,sp]=await Promise.all([adminApi.doctors(),adminApi.specialties()]);setDoctors(dr.data);setSpecialties(sp.data);}catch(e){setErr(getApiErrorMessage(e,'Không thể thêm bác sĩ'))}};
  const saveDoctor=async()=>{try{setErr('');const email=(editingDoctor.email||'').trim().toLowerCase();if(!email)throw new Error('Email đăng nhập không được để trống');const payload={email,full_name:editingDoctor.full_name.trim(),phone:editingDoctor.phone?.trim()||'',license_no:editingDoctor.license_no.trim(),bio:editingDoctor.bio||'',room:editingDoctor.room.trim(),specialty_id:Number(editingDoctor.specialty_id)};const r=await adminApi.updateDoctor(editingDoctor.doctor_id,payload);const updated=r.data||{};setDoctors(prev=>prev.map(d=>d.doctor_id===editingDoctor.doctor_id?{...d,...payload,email:updated.login_email||updated.email||email,specialty_name:(specialties.find(s=>s.id===Number(payload.specialty_id))||{}).name||d.specialty_name}:d));try{const dr=await adminApi.doctors();setDoctors(Array.isArray(dr.data)?dr.data:[])}catch{}setEditingDoctor(null);flash(`Đã cập nhật bác sĩ. Email đăng nhập: ${updated.login_email||updated.email||email}`);}catch(e){setErr(getApiErrorMessage(e,'Không thể cập nhật bác sĩ'))}};
  const saveUser=async()=>{try{await adminApi.updateUser(editingUser.id,{full_name:editingUser.full_name,email:editingUser.email,phone:editingUser.phone,role:editingUser.role,is_active:editingUser.is_active});setEditingUser(null);flash('Đã cập nhật tài khoản và vai trò');loadUsers();}catch(e){setErr(getApiErrorMessage(e,'Không thể cập nhật tài khoản'))}};
  const doResetPassword=async()=>{try{if(!resetPassword||resetPassword.length<6)throw new Error('Mật khẩu phải có ít nhất 6 ký tự');await adminApi.resetPassword(resetUser.id,resetPassword);setResetUser(null);setResetPassword('');flash('Đã đặt lại mật khẩu tài khoản');}catch(e){setErr(getApiErrorMessage(e,'Không thể đặt lại mật khẩu'))}};
  const emptyService=()=>({specialty_id:specialties[0]?.id||'',code:'',name:'',description:'',price:0,active:true});
  const saveService=async()=>{try{setErr('');if(!serviceForm.specialty_id) throw new Error('Vui lòng chọn chuyên khoa');if(!serviceForm.code.trim()) throw new Error('Vui lòng nhập mã dịch vụ');if(!serviceForm.name.trim()) throw new Error('Vui lòng nhập tên dịch vụ');const price=Number(serviceForm.price);if(!Number.isFinite(price)||price<0) throw new Error('Giá niêm yết không hợp lệ');const payload={...serviceForm,specialty_id:Number(serviceForm.specialty_id),code:serviceForm.code.trim(),name:serviceForm.name.trim(),description:(serviceForm.description||'').trim(),price};const wasEditing=Boolean(editingService);if(wasEditing) await adminApi.updateService(editingService.id,payload);else await adminApi.createService(payload);const refreshed=await adminApi.services();setServices(refreshed.data);setEditingService(null);setShowServiceForm(false);setServiceForm(emptyService());flash(wasEditing?'Đã cập nhật bảng giá':'Đã tạo dịch vụ');}catch(e){setErr(getApiErrorMessage(e,'Không thể lưu dịch vụ'))}};
  const saveReschedule=async()=>{try{await bookingApi.reschedule(rescheduling.id,{appointment_date:rescheduling.date,start_time:rescheduling.start_time});setRescheduling(null);flash('Đã cập nhật thời gian khám');receptionApi.appointments(appointmentDate).then(r=>setAppointments(r.data));}catch(e){setErr(getApiErrorMessage(e,'Không thể đổi thời gian khám'))}};
  const applyShiftPreset=preset=>{setSelectedShift(preset.key);setScheduleForm(f=>({...f,start_time:preset.start_time,end_time:preset.end_time,slot_minutes:preset.slot_minutes}))};
  const weekdayNames=['Thứ 2','Thứ 3','Thứ 4','Thứ 5','Thứ 6','Thứ 7'];
  const presetForRow=row=>SHIFT_PRESETS.find(p=>p.start_time===row.start_time&&p.end_time===row.end_time&&Number(p.slot_minutes)===Number(row.slot_minutes));
  const buildWeeklyRows=()=>{
    const rows=[];
    for(let weekday=0;weekday<6;weekday++) {
      const existing=scheduleRows.filter(r=>Number(r.weekday)===weekday);
      if(existing.length) rows.push(...existing.map(r=>({...r})));
      else rows.push({id:null,doctor_id:Number(scheduleDoctorId),weekday,start_time:'08:00',end_time:'17:00',slot_minutes:30,__preset:'office',__new:true});
    }
    return rows;
  };
  const addWeeklyShift=weekday=>setScheduleRows(prev=>{
    const existing=prev.filter(r=>Number(r.weekday)===weekday);
    if(existing.length) return [...prev,{id:null,doctor_id:Number(scheduleDoctorId),weekday,start_time:'13:00',end_time:'17:00',slot_minutes:30,__preset:'shift2',__new:true}];
    return [...prev,{id:null,doctor_id:Number(scheduleDoctorId),weekday,start_time:'08:00',end_time:'17:00',slot_minutes:30,__preset:'office',__new:true},{id:null,doctor_id:Number(scheduleDoctorId),weekday,start_time:'13:00',end_time:'17:00',slot_minutes:30,__preset:'shift2',__new:true}];
  });
  const updateWeeklyLocal=(key,field,value)=>setScheduleRows(prev=>prev.map(r=>r===key?{...r,[field]:field==='weekday'||field==='slot_minutes'?Number(value):value}:r));
  const applyWeeklyPreset=(row,preset)=>setScheduleRows(prev=>prev.map(r=>r===row?{...r,__preset:preset.key,start_time:preset.start_time,end_time:preset.end_time,slot_minutes:preset.slot_minutes}:r));
  const saveWeeklySchedule=async()=>{
    if(!scheduleDoctorId) return;
    setErr('');
    try {
      const current=buildWeeklyRows();
      const touched=current.filter(r=>r.__new||r.id);
      for(const row of touched){
        const payload={weekday:Number(row.weekday),start_time:row.start_time,end_time:row.end_time,slot_minutes:Number(row.slot_minutes)};
        if(row.id) await doctorApi.updateSchedule(Number(scheduleDoctorId),row.id,payload);
        else await doctorApi.addSchedule(Number(scheduleDoctorId),payload);
      }
      const r=await doctorApi.schedules(Number(scheduleDoctorId));
      setScheduleRows(r.data);
      flash('Đã lưu lịch làm việc từ Thứ 2 đến Thứ 7.');
    } catch(e) { setErr(getApiErrorMessage(e,'Không thể lưu lịch làm việc')); }
  };
  const saveSchedule=async()=>{try{await doctorApi.addSchedule(Number(scheduleDoctorId),{...scheduleForm,slot_minutes:Number(scheduleForm.slot_minutes)});flash('Đã thêm ca làm việc. Bạn vẫn có thể chỉnh thời gian linh hoạt ở từng ca bên dưới.');const r=await doctorApi.schedules(Number(scheduleDoctorId));setScheduleRows(r.data);}catch(e){setErr(getApiErrorMessage(e,'Không thể thêm ca làm việc'))}};
  const updateSchedule=async row=>{try{await doctorApi.updateSchedule(Number(scheduleDoctorId),row.id,{weekday:row.weekday,start_time:row.start_time,end_time:row.end_time,slot_minutes:Number(row.slot_minutes)});flash('Đã cập nhật ca làm việc');const r=await doctorApi.schedules(Number(scheduleDoctorId));setScheduleRows(r.data);}catch(e){setErr(getApiErrorMessage(e,'Không thể cập nhật ca làm việc'))}};
  const saveDayOff=async()=>{try{await doctorApi.addDayOff(Number(scheduleDoctorId),dayOffForm);flash('Đã thêm ngày nghỉ');const r=await doctorApi.daysOff(Number(scheduleDoctorId));setScheduleDaysOff(r.data);setDayOffForm({date:'',reason:'Ngày nghỉ'});}catch(e){setErr(getApiErrorMessage(e,'Không thể thêm ngày nghỉ'))}};
  const tabs=[['overview','Tổng quan'],['patients','Bệnh nhân'],['specialties','Chuyên khoa'],['doctors','Bác sĩ'],['services','Dịch vụ & giá'],['schedules','Lịch làm việc'],['appointments','Lịch khám'],['users','Tài khoản']];
  return <div><Title title="Quản trị hệ thống" text="Quản lý dữ liệu nền, thời gian khám, bảng giá và hồ sơ bệnh nhân/bác sĩ."/>
    <div className="flex flex-wrap gap-2 mb-6">{tabs.map(([k,l])=><button key={k} onClick={()=>{setTab(k);setErr('')}} className={`px-4 py-2.5 rounded-xl text-sm font-bold border ${tab===k?'bg-[#eaf4ff] text-[#2f80ed] border-[#bfddfa]':'bg-white text-[#617d98] border-[#dcecff]'}`}>{l}</button>)}</div>
    {tab==='overview'&&<><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-5">{[['Tổng lịch hôm nay',d?.total_today],['Đang chờ',d?.waiting],['Đang khám',d?.in_progress],['Hoàn thành',d?.completed],['Đã hủy',d?.cancelled],['Không đến khám',d?.no_show]].map(([l,v])=><div key={l} className="card rounded-2xl bg-white p-6"><div className="text-sm text-[#7893ab]">{l}</div><div className="text-3xl font-black text-[#24527a] mt-2">{v??'—'}</div></div>)}</div><div className="card rounded-3xl bg-white mt-6 p-6"><div className="flex items-center gap-3"><CalendarClock className="text-[#2f80ed]"/><div><div className="font-extrabold text-[#274f74]">Ngày thống kê</div><div className="text-sm text-[#849bb0]">{d?.date||'Đang tải…'}</div></div></div></div></>}
    {tab==='patients'&&<div className="card rounded-3xl bg-white p-5"><div className="flex gap-2 mb-4"><input className="input flex-1" placeholder="Tìm mã BN / họ tên / SĐT / email" value={patientQ} onChange={e=>setPatientQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&adminApi.patients(patientQ).then(r=>setPatients(r.data))}/><button className="btn btn-soft" onClick={()=>adminApi.patients(patientQ).then(r=>setPatients(r.data))}>Tìm</button></div><div className="space-y-3">{patients.map(p=><div key={p.patient_id} className="rounded-2xl border border-[#dcecff] p-4"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><div className="font-black text-[#315b83]">{p.full_name}</div><div className="text-xs text-[#7892aa] mt-1">{p.patient_code} · {p.phone||'Chưa có SĐT'} · {p.email}</div><div className="text-xs text-[#7892aa] mt-1">Ngày sinh: {p.date_of_birth||'—'} · Giới tính: {p.gender||'—'}</div></div><button className="btn btn-primary text-xs" onClick={()=>setEditingPatient({...p})}>Chỉnh sửa</button></div></div>)}{!patients.length&&<Empty text="Chưa có bệnh nhân phù hợp."/>}</div></div>}
    {tab==='specialties'&&<div className="card rounded-3xl bg-white p-5"><div className="flex items-center justify-between mb-4"><div><div className="font-extrabold text-[#234d73]">Danh mục chuyên khoa</div><div className="text-sm text-[#7f97ac]">Thêm chuyên khoa mới sẽ xuất hiện ngay khi bệnh nhân chọn chuyên khoa và khi quản lý bác sĩ/dịch vụ.</div></div><button className="btn btn-primary text-xs" onClick={()=>{setSpecialtyForm({name:'',description:''});setShowSpecialtyForm(true)}}>+ Thêm chuyên khoa</button></div><div className="grid md:grid-cols-2 gap-3">{specialties.map(s=><div key={s.id} className="rounded-2xl border border-[#dcecff] p-4"><div className="font-black text-[#315b83]">{s.name}</div><div className="text-sm text-[#7892aa] mt-1">{s.description||'Chưa có mô tả'}</div><div className="text-xs text-[#9ab0c4] mt-2">Mã hệ thống: CK-{String(s.id).padStart(4,'0')}</div></div>)}{!specialties.length&&<Empty text="Chưa có chuyên khoa."/>}</div></div>}
    {tab==='doctors'&&<div className="card rounded-3xl bg-white p-5"><div className="flex items-center justify-between mb-4"><div><div className="font-extrabold text-[#234d73]">Quản lý bác sĩ</div><div className="text-sm text-[#7f97ac]">Thêm bác sĩ mới sẽ tự tạo tài khoản DOCTOR và liên kết chuyên khoa.</div></div><button className="btn btn-primary text-xs" onClick={()=>{setDoctorForm({full_name:'',email:'',phone:'',password:'123456',license_no:'',bio:'',room:'101',specialty_id:specialties[0]?.id||''});setShowDoctorForm(true)}}>+ Thêm bác sĩ</button></div><div className="space-y-3">{doctors.map(x=><div key={x.doctor_id} className="rounded-2xl border border-[#dcecff] p-4 flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><div className="font-black text-[#315b83]">{x.full_name}</div><div className="text-xs text-[#7892aa] mt-1">{x.license_no} · {x.specialty_name||'Chưa phân chuyên khoa'} · Phòng {x.room}</div><div className="text-xs text-[#7892aa] mt-1">{x.phone||'Chưa có SĐT'} · {x.email}</div></div><button className="btn btn-primary text-xs" onClick={()=>setEditingDoctor({...x})}>Chỉnh sửa</button></div>)}{!doctors.length&&<Empty text="Chưa có bác sĩ."/>}</div></div>}
    {tab==='services'&&<div className="grid xl:grid-cols-[1.35fr_.8fr] gap-5"><section className="card rounded-3xl bg-white p-5"><div className="flex items-center justify-between mb-4"><div><div className="font-extrabold text-[#234d73]">Bảng giá niêm yết</div><div className="text-sm text-[#7f97ac]">Giá được lấy từ database khi bệnh nhân đặt lịch.</div></div><button className="btn btn-primary text-xs" onClick={()=>{setEditingService(null);setServiceForm(emptyService());setShowServiceForm(true);setErr('')}}>+ Thêm dịch vụ</button></div><div className="space-y-3">{services.map(x=><div key={x.id} className="rounded-2xl border border-[#dcecff] p-4 flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><div className="font-black text-[#315b83]">{x.name}</div><div className="text-xs text-[#7892aa] mt-1">{x.code} · {x.specialty_name}</div><div className="font-black text-[#2f80ed] mt-1">{money(x.price)}</div></div><button className="btn btn-soft text-xs" onClick={()=>{setEditingService(x);setServiceForm({specialty_id:x.specialty_id,code:x.code,name:x.name,description:x.description||'',price:x.price,active:x.active});setShowServiceForm(true);setErr('')}}>Sửa giá / dịch vụ</button></div>)}</div></section><section className="card rounded-3xl bg-white p-5">{showServiceForm&&<><div className="font-extrabold text-[#234d73]">{editingService?'Chỉnh sửa dịch vụ':'Tạo dịch vụ'}</div><div className="space-y-3 mt-4"><select className="input" value={serviceForm.specialty_id} onChange={e=>setServiceForm({...serviceForm,specialty_id:e.target.value})}><option value="">Chọn chuyên khoa</option>{specialties.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input className="input" placeholder="Mã dịch vụ" value={serviceForm.code} onChange={e=>setServiceForm({...serviceForm,code:e.target.value})}/><input className="input" placeholder="Tên dịch vụ" value={serviceForm.name} onChange={e=>setServiceForm({...serviceForm,name:e.target.value})}/><textarea className="input min-h-24" placeholder="Mô tả" value={serviceForm.description} onChange={e=>setServiceForm({...serviceForm,description:e.target.value})}/><label><div className="label">Giá niêm yết</div><input className="input" type="number" min="0" value={serviceForm.price} onChange={e=>setServiceForm({...serviceForm,price:e.target.value})}/></label><label className="flex items-center gap-2 text-sm font-semibold text-[#4d6f8d]"><input type="checkbox" checked={serviceForm.active} onChange={e=>setServiceForm({...serviceForm,active:e.target.checked})}/> Đang áp dụng</label><div className="flex gap-2"><button className="btn btn-primary flex-1" onClick={saveService}>Lưu</button><button className="btn btn-soft" onClick={()=>{setEditingService(null);setShowServiceForm(false);setServiceForm(emptyService())}}>Hủy</button></div></div></>}</section></div>}
    {tab==='schedules'&&<div className="grid xl:grid-cols-[1.45fr_.9fr] gap-5">
      <section className="card rounded-3xl bg-white p-5">
        <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-3">
          <div><div className="font-extrabold text-[#234d73]">Lịch làm việc bác sĩ</div><div className="text-sm text-[#7f97ac] mt-1">Mặc định hiển thị Thứ 2 → Thứ 7. Mỗi ngày chọn ca nhanh hoặc chỉnh giờ, thời lượng linh hoạt theo thực tế.</div></div>
          <button disabled={!scheduleDoctorId} className="btn btn-primary text-sm disabled:opacity-50" onClick={saveWeeklySchedule}>Lưu lịch Thứ 2–Thứ 7</button>
        </div>
        <select className="input mt-4" value={scheduleDoctorId} onChange={e=>setScheduleDoctorId(e.target.value)}><option value="">Chọn bác sĩ</option>{scheduleDoctors.map(x=><option key={x.doctor_id} value={x.doctor_id}>{x.full_name} · {x.specialty_name||'Chưa phân chuyên khoa'}</option>)}</select>
        {!scheduleDoctorId&&<div className="mt-5"><Empty text="Chọn bác sĩ để cấu hình lịch từ Thứ 2 đến Thứ 7."/></div>}
        {scheduleDoctorId&&<div className="mt-5 space-y-3">{weekdayNames.map((day,weekday)=>{
          const dayRows=scheduleRows.filter(r=>Number(r.weekday)===weekday);
          const rows=dayRows.length?dayRows:[{id:null,weekday,start_time:'08:00',end_time:'17:00',slot_minutes:30,__new:true,__preset:'office'}];
          return <div key={weekday} className="rounded-2xl border border-[#dcecff] bg-[#fbfdff] p-4">
            <div className="flex items-center justify-between gap-3 mb-3"><div className="font-black text-[#2f5c83]">{day}</div><button type="button" className="text-xs font-bold text-[#2f80ed]" onClick={()=>addWeeklyShift(weekday)}>+ Thêm ca</button></div>
            <div className="space-y-2">{rows.map((row,rowIdx)=><div key={row.id||`${weekday}-${rowIdx}`} className="grid lg:grid-cols-[145px_1fr_1fr_135px] gap-2 items-center">
              <select className="input text-sm" value={row.__preset||presetForRow(row)?.key||'custom'} onChange={e=>{const p=SHIFT_PRESETS.find(x=>x.key===e.target.value); if(p) applyWeeklyPreset(row,p); else setScheduleRows(prev=>prev.map(r=>r===row?{...r,__preset:'custom'}:r));}}>
                <option value="office">Ca hành chính</option><option value="shift1">Ca 1 - Buổi sáng</option><option value="shift2">Ca 2 - Buổi chiều</option><option value="evening">Ca tối</option><option value="oncall">Ca trực đêm</option><option value="custom">Tùy chỉnh</option>
              </select>
              <input className="input text-sm" type="time" value={row.start_time} onChange={e=>setScheduleRows(prev=>prev.map(r=>r===row?{...r,start_time:e.target.value,__preset:'custom'}:r))}/>
              <input className="input text-sm" type="time" value={row.end_time} onChange={e=>setScheduleRows(prev=>prev.map(r=>r===row?{...r,end_time:e.target.value,__preset:'custom'}:r))}/>
              <select className="input text-sm" value={row.slot_minutes} onChange={e=>setScheduleRows(prev=>prev.map(r=>r===row?{...r,slot_minutes:Number(e.target.value),__preset:'custom'}:r))}>{[15,20,30,45,60].map(x=><option key={x} value={x}>{x} phút/lượt</option>)}</select>
            </div>)}</div></div>
        })}</div>}
        <div className="mt-4 rounded-xl bg-[#edf6ff] p-3 text-xs text-[#5d7d9b]">Chọn ca mẫu sẽ tự điền giờ. Bạn vẫn có thể đổi giờ bắt đầu/kết thúc hoặc thời lượng ngay trên từng ngày. Có thể thêm nhiều ca trong cùng một ngày nếu khung giờ không trùng nhau.</div>
      </section>
      <section className="card rounded-3xl bg-white p-5"><div className="font-extrabold text-[#234d73]">Ngày nghỉ</div><div className="text-sm text-[#7f97ac] mt-1">Ngày nghỉ sẽ khiến Booking không sinh slot cho bác sĩ.</div><div className="grid md:grid-cols-[1fr_1.6fr] gap-3 mt-4"><input className="input" type="date" value={dayOffForm.date} onChange={e=>setDayOffForm({...dayOffForm,date:e.target.value})}/><input className="input" value={dayOffForm.reason} onChange={e=>setDayOffForm({...dayOffForm,reason:e.target.value})} placeholder="Lý do nghỉ"/></div><button disabled={!scheduleDoctorId||!dayOffForm.date} className="btn btn-primary mt-4 disabled:opacity-50" onClick={saveDayOff}>Thêm ngày nghỉ</button><div className="mt-5 space-y-2">{scheduleDaysOff.map(x=><div key={x.id} className="rounded-2xl bg-[#fff7f2] border border-[#f5e1d1] p-3 text-sm text-[#7c604a]">{x.date} · {x.reason||'Ngày nghỉ'}</div>)}{!scheduleDaysOff.length&&<Empty text="Chưa có ngày nghỉ."/>}</div></section>
    </div>}
    {tab==='users'&&<div className="card rounded-3xl bg-white p-5">
      <div className="flex flex-col lg:flex-row lg:items-end gap-3 mb-4">
        <div className="flex gap-2 flex-wrap">
          {[['staff','Nhân viên bệnh viện'],['customers','Khách hàng']].map(([k,l])=><button key={k} onClick={()=>{setUserGroup(k);setUserQ('')}} className={`px-4 py-2.5 rounded-xl text-sm font-bold border ${userGroup===k?'bg-[#eaf4ff] text-[#2f80ed] border-[#bfddfa]':'bg-white text-[#617d98] border-[#dcecff]'}`}>{l}</button>)}
        </div>
        <label className="flex-1"><div className="label">Tìm tài khoản</div><input className="input" placeholder={userGroup==='staff'?'Họ tên / email / SĐT / mã user':'Họ tên / email / SĐT / mã user / mã bệnh nhân'} value={userQ} onChange={e=>setUserQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&loadUsers()}/></label>
        <button className="btn btn-soft" onClick={loadUsers}>Tìm</button>
      </div>
      <div className="mb-4 rounded-2xl bg-[#f7fbff] p-4 text-sm text-[#6e88a0]">{userGroup==='staff'?<><b className="text-[#315b83]">Nhân viên bệnh viện</b> gồm <b>bác sĩ</b> và <b>nhân viên tiếp nhận</b>. Admin dùng khu vực này để kiểm tra tài khoản đăng nhập, trạng thái hoạt động và đặt lại mật khẩu.</>:<><b className="text-[#315b83]">Khách hàng</b> là người bệnh có tài khoản đăng nhập và hồ sơ bệnh nhân. Mã bệnh nhân được hiển thị cùng tài khoản để dễ đối chiếu.</>}</div>
      <div className="space-y-3">{users.map(u=><div key={u.id} className="rounded-2xl border border-[#dcecff] p-4 flex flex-col lg:flex-row lg:items-center lg:justify-between gap-3"><div><div className="font-black text-[#315b83]">{u.full_name}</div><div className="text-xs text-[#7892aa] mt-1">USER-{String(u.id).padStart(6,'0')} · {u.email} · {u.phone||'Chưa có SĐT'}</div><div className="flex gap-2 mt-2 flex-wrap"><span className="badge bg-[#edf6ff] text-[#2f6fae]">{{PATIENT:'Khách hàng',RECEPTIONIST:'Nhân viên tiếp nhận',DOCTOR:'Bác sĩ',ADMIN:'Quản trị viên'}[u.role]||u.role}</span><span className={`badge ${u.is_active?'bg-[#eaf8ef] text-[#16733b]':'bg-[#fff0ef] text-[#b42318]'}`}>{u.is_active?'Đang hoạt động':'Đã khóa'}</span>{u.patient_code&&<span className="badge bg-[#f7fbff] text-[#627f99]">{u.patient_code}</span>}</div></div><div className="flex gap-2"><button className="btn btn-soft text-xs" onClick={()=>setEditingUser({...u})}>Chỉnh sửa</button><button className="btn btn-primary text-xs" onClick={()=>{setResetUser(u);setResetPassword('')}}>Đặt lại mật khẩu</button></div></div>)}{!users.length&&<Empty text={userGroup==='staff'?'Chưa có nhân viên phù hợp.':'Chưa có khách hàng phù hợp.'}/>}</div>
    </div>}
    {editingPatient&&<Modal title="Chỉnh sửa bệnh nhân" onClose={()=>setEditingPatient(null)}><div className="space-y-3"><input className="input" value={editingPatient.full_name} onChange={e=>setEditingPatient({...editingPatient,full_name:e.target.value})} placeholder="Họ tên"/><input className="input" value={editingPatient.email} onChange={e=>setEditingPatient({...editingPatient,email:e.target.value})} placeholder="Email"/><input className="input" value={editingPatient.phone||''} onChange={e=>setEditingPatient({...editingPatient,phone:e.target.value})} placeholder="Số điện thoại"/><input className="input" type="date" value={editingPatient.date_of_birth||''} onChange={e=>setEditingPatient({...editingPatient,date_of_birth:e.target.value})}/><select className="input" value={editingPatient.gender||''} onChange={e=>setEditingPatient({...editingPatient,gender:e.target.value})}><option value="">Giới tính</option><option>Nam</option><option>Nữ</option><option>Khác</option></select><textarea className="input min-h-20" value={editingPatient.address||''} onChange={e=>setEditingPatient({...editingPatient,address:e.target.value})} placeholder="Địa chỉ"/><textarea className="input min-h-20" value={editingPatient.emergency_contact||''} onChange={e=>setEditingPatient({...editingPatient,emergency_contact:e.target.value})} placeholder="Liên hệ khẩn cấp"/><div className="grid grid-cols-2 gap-2"><button className="btn btn-primary w-full" onClick={savePatient}>Lưu thay đổi</button><button className="btn btn-soft w-full" onClick={()=>{setResetUser({id:editingPatient.user_id,full_name:editingPatient.full_name,email:editingPatient.email});setResetPassword('')}}>Đặt lại mật khẩu</button></div></div></Modal>}
    {editingDoctor&&<Modal title="Chỉnh sửa bác sĩ" onClose={()=>setEditingDoctor(null)}><div className="space-y-3"><input className="input" value={editingDoctor.full_name} onChange={e=>setEditingDoctor({...editingDoctor,full_name:e.target.value})} placeholder="Họ tên"/><input className="input" type="email" value={editingDoctor.email||''} onChange={e=>setEditingDoctor({...editingDoctor,email:e.target.value})} placeholder="Email đăng nhập *"/><input className="input" value={editingDoctor.phone||''} onChange={e=>setEditingDoctor({...editingDoctor,phone:e.target.value})} placeholder="Số điện thoại"/><input className="input" value={editingDoctor.license_no} onChange={e=>setEditingDoctor({...editingDoctor,license_no:e.target.value})} placeholder="Số giấy phép"/><select className="input" value={editingDoctor.specialty_id||''} onChange={e=>setEditingDoctor({...editingDoctor,specialty_id:e.target.value})}><option value="">Chọn chuyên khoa</option>{specialties.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input className="input" value={editingDoctor.room} onChange={e=>setEditingDoctor({...editingDoctor,room:e.target.value})} placeholder="Phòng khám"/><textarea className="input min-h-24" value={editingDoctor.bio||''} onChange={e=>setEditingDoctor({...editingDoctor,bio:e.target.value})} placeholder="Giới thiệu bác sĩ"/><div className="grid grid-cols-2 gap-2"><button className="btn btn-primary w-full" onClick={saveDoctor}>Lưu thay đổi</button><button className="btn btn-soft w-full" onClick={()=>{setResetUser({id:editingDoctor.user_id,full_name:editingDoctor.full_name,email:editingDoctor.email});setResetPassword('')}}>Đặt lại mật khẩu</button></div></div></Modal>}
    {showSpecialtyForm&&<Modal title="Thêm chuyên khoa" onClose={()=>setShowSpecialtyForm(false)}><div className="space-y-3"><input className="input" value={specialtyForm.name} onChange={e=>setSpecialtyForm({...specialtyForm,name:e.target.value})} placeholder="Tên chuyên khoa *"/><textarea className="input min-h-28" value={specialtyForm.description} onChange={e=>setSpecialtyForm({...specialtyForm,description:e.target.value})} placeholder="Mô tả chuyên khoa"/><button disabled={!specialtyForm.name.trim()} className="btn btn-primary w-full disabled:opacity-50" onClick={saveSpecialty}>Tạo chuyên khoa</button></div></Modal>}
    {showDoctorForm&&<Modal title="Thêm bác sĩ mới" onClose={()=>setShowDoctorForm(false)}><div className="space-y-3"><input className="input" value={doctorForm.full_name} onChange={e=>setDoctorForm({...doctorForm,full_name:e.target.value})} placeholder="Họ tên bác sĩ *"/><input className="input" type="email" value={doctorForm.email} onChange={e=>setDoctorForm({...doctorForm,email:e.target.value})} placeholder="Email đăng nhập *"/><input className="input" value={doctorForm.phone} onChange={e=>setDoctorForm({...doctorForm,phone:e.target.value})} placeholder="Số điện thoại (không bắt buộc)"/><input className="input" type="password" value={doctorForm.password} onChange={e=>setDoctorForm({...doctorForm,password:e.target.value})} placeholder="Mật khẩu khởi tạo *"/><input className="input" value={doctorForm.license_no} onChange={e=>setDoctorForm({...doctorForm,license_no:e.target.value})} placeholder="Số giấy phép *"/><select className="input" value={doctorForm.specialty_id} onChange={e=>setDoctorForm({...doctorForm,specialty_id:e.target.value})}><option value="">Chọn chuyên khoa *</option>{specialties.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input className="input" value={doctorForm.room} onChange={e=>setDoctorForm({...doctorForm,room:e.target.value})} placeholder="Phòng khám *"/><textarea className="input min-h-24" value={doctorForm.bio} onChange={e=>setDoctorForm({...doctorForm,bio:e.target.value})} placeholder="Giới thiệu bác sĩ"/><div className="rounded-xl bg-[#edf6ff] p-3 text-sm text-[#527899]">Sau khi tạo, bác sĩ xuất hiện ngay trong danh sách đặt lịch của bệnh nhân. Mật khẩu khởi tạo có thể đổi sau khi đăng nhập.</div><button disabled={!doctorForm.full_name.trim()||!doctorForm.email.trim()||!doctorForm.password||!doctorForm.license_no.trim()||!doctorForm.specialty_id||!doctorForm.room.trim()} className="btn btn-primary w-full disabled:opacity-50" onClick={saveNewDoctor}>Tạo bác sĩ</button></div></Modal>}
    {editingUser&&<Modal title="Chỉnh sửa tài khoản" onClose={()=>setEditingUser(null)}><div className="space-y-3"><input className="input" value={editingUser.full_name} onChange={e=>setEditingUser({...editingUser,full_name:e.target.value})} placeholder="Họ tên"/><input className="input" type="email" value={editingUser.email} onChange={e=>setEditingUser({...editingUser,email:e.target.value})} placeholder="Email đăng nhập"/><input className="input" value={editingUser.phone||''} onChange={e=>setEditingUser({...editingUser,phone:e.target.value})} placeholder="Số điện thoại"/><label><div className="label">Vai trò</div><select className="input" value={editingUser.role} onChange={e=>setEditingUser({...editingUser,role:e.target.value})}><option value="DOCTOR">Bác sĩ</option><option value="RECEPTIONIST">Nhân viên tiếp nhận</option><option value="ADMIN">Quản trị viên</option><option value="PATIENT">Bệnh nhân</option></select></label><label className="flex items-center gap-2 text-sm font-semibold text-[#4d6f8d]"><input type="checkbox" checked={editingUser.is_active} onChange={e=>setEditingUser({...editingUser,is_active:e.target.checked})}/> Tài khoản đang hoạt động</label><div className="rounded-xl bg-[#f7fbff] p-3 text-sm text-[#6f89a1]">Admin có thể gán lại vai trò. Vai trò <b>Bác sĩ</b>/<b>Bệnh nhân</b> chỉ được gán khi tài khoản đã có hồ sơ tương ứng.</div><button className="btn btn-primary w-full" onClick={saveUser}>Lưu thay đổi</button></div></Modal>}
    {resetUser&&<Modal title={`Đặt lại mật khẩu · ${resetUser.full_name}`} onClose={()=>{setResetUser(null);setResetPassword('')}}><div className="space-y-3"><div className="rounded-xl bg-[#edf6ff] p-3 text-sm text-[#527899]">Tài khoản: {resetUser.email}</div><input className="input" type="password" value={resetPassword} onChange={e=>setResetPassword(e.target.value)} placeholder="Mật khẩu mới (ít nhất 6 ký tự)"/><button disabled={resetPassword.length<6} className="btn btn-primary w-full disabled:opacity-50" onClick={doResetPassword}>Xác nhận đặt lại mật khẩu</button></div></Modal>}
    {rescheduling&&<Modal title="Điều chỉnh thời gian khám" onClose={()=>setRescheduling(null)}><div className="space-y-3"><label><div className="label">Ngày mới</div><input className="input" type="date" value={rescheduling.date} onChange={e=>setRescheduling({...rescheduling,date:e.target.value})}/></label><label><div className="label">Khung giờ còn trống</div><select className="input" value={rescheduling.start_time} onChange={e=>setRescheduling({...rescheduling,start_time:e.target.value})}><option value="">Chọn giờ</option>{rescheduleSlots.map(slot=><option key={slot.start_time} value={slot.start_time}>{slot.start_time} - {slot.end_time}</option>)}</select></label><div className="text-xs text-[#7892aa]">Hệ thống tự tải slot theo lịch làm việc, ngày nghỉ và các lịch đã đặt.</div><button disabled={!rescheduling.start_time||!rescheduleSlots.some(x=>x.start_time===rescheduling.start_time)} className="btn btn-primary w-full disabled:opacity-50" onClick={saveReschedule}>Xác nhận đổi lịch</button></div></Modal>}
    {msg&&<div className="mt-4 rounded-xl bg-[#edf6ff] text-[#2f6aa3] p-3 text-sm">{msg}</div>}{err&&<div className="mt-4 rounded-xl bg-[#fff0ef] text-[#b42318] p-3 text-sm">{err}</div>}
  </div>
}

function Modal({title,onClose,children}){return <div className="fixed inset-0 z-50 bg-black/30 grid place-items-center p-4"><div className="w-full max-w-lg max-h-[90vh] overflow-auto rounded-3xl bg-white shadow-xl"><div className="flex items-center justify-between p-5 border-b border-[#eef5fb]"><div className="font-black text-[#234d73]">{title}</div><button onClick={onClose} className="text-xl text-[#8aa1b5]">×</button></div><div className="p-5">{children}</div></div></div>}

function Metric({icon:Icon,label,value}){return <div className="card rounded-2xl bg-white p-5 flex items-center gap-4"><div className="h-11 w-11 rounded-xl bg-[#edf6ff] text-[#2f80ed] grid place-items-center"><Icon size={21}/></div><div><div className="text-xs font-bold uppercase tracking-[.11em] text-[#86a2bb]">{label}</div><div className="text-2xl font-black text-[#244c72] mt-1">{value}</div></div></div>}
function Info({label,value}){return <div><div className="text-[11px] uppercase tracking-wider font-bold text-[#8da5ba]">{label}</div><div className="text-sm font-semibold text-[#335b7e] mt-1 break-words">{value||'—'}</div></div>}
function Title({title,text}){return <div className="mb-6"><div className="text-3xl font-black text-[#17395f]">{title}</div><div className="mt-1 text-[#7892aa]">{text}</div></div>}
function Empty({text}){return <div className="rounded-2xl border border-dashed border-[#cfe1f3] p-10 text-center text-[#7892aa]">{text}</div>}
