import {useEffect,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {CalendarPlus,ChevronRight,Clock3,UserRound,Hospital,Stethoscope,CheckCircle2,Phone,MapPin,ClipboardCheck,AlertCircle,WalletCards,QrCode,CreditCard,ReceiptText} from 'lucide-react';
import {useAuth} from '../context/AuthContext';
import {authApi,bookingApi,masterApi,paymentApi,getApiErrorMessage} from '../services/api';

const STATUS={CONFIRMED:['Đã xác nhận','confirmed'],CHECKED_IN:['Đã tiếp nhận','checked_in'],WAITING:['Đang chờ khám','waiting'],IN_PROGRESS:['Đang khám','in_progress'],COMPLETED:['Đã khám xong','completed'],CANCELLED:['Đã hủy','cancelled'],NO_SHOW:['Không đến khám','no_show']};
const visitLabel=v=>v==='WALK_IN'?'Khám không đặt lịch':'Đặt lịch trước';
const statusLabel=s=>STATUS[s]?.[0]||s;
const paymentLabel=s=>({UNPAID:'Chưa thanh toán',PENDING:'Chờ thanh toán',PAID:'Đã thanh toán',REFUND_PENDING:'Chờ hoàn tiền',REFUNDED:'Đã hoàn tiền'}[s]||'Chưa cập nhật');
const appointmentCode=id=>`AP-${String(id).padStart(6,'0')}`;
const today=()=>new Date().toISOString().slice(0,10);
const money=n=>new Intl.NumberFormat('vi-VN').format(n||0)+' ₫';

export function PatientHome(){
  const {user}=useAuth(); const [apps,setApps]=useState([]);
  useEffect(()=>{bookingApi.mine().then(r=>setApps(r.data)).catch(()=>{})},[]);
  const upcoming=apps.filter(a=>['CONFIRMED','CHECKED_IN','WAITING','IN_PROGRESS'].includes(a.status)).sort((a,b)=>(a.appointment_date+a.start_time).localeCompare(b.appointment_date+b.start_time)).slice(0,3);
  const unpaid=apps.filter(a=>['UNPAID','PENDING'].includes(a.payment_status));
  return <div>
    <Hero title={`Xin chào, ${user?.full_name?.split(' ').slice(-1)[0]||'bạn'} 👋`} text="Theo dõi lịch khám, thông tin bác sĩ, thanh toán và kết quả khám của bạn." action="Đặt lịch khám" to="/patient/book" icon={CalendarPlus}/>
    <div className="grid lg:grid-cols-4 gap-5 mt-6"><InfoCard icon={CalendarPlus} label="Tổng lịch khám" value={apps.length}/><InfoCard icon={Clock3} label="Lịch đang xử lý" value={upcoming.length}/><InfoCard icon={WalletCards} label="Chưa thanh toán" value={unpaid.length}/><InfoCard icon={Hospital} label="Trạng thái hệ thống" value="Hoạt động"/></div>
    {unpaid.length>0&&<section className="card rounded-3xl bg-[#fffaf0] border border-[#f4e3b7] mt-7 p-5"><div className="flex items-center justify-between gap-3"><div><div className="font-extrabold text-[#7b5d00]">Bạn có lịch chưa thanh toán</div><div className="text-sm text-[#9b7b25] mt-1">Kiểm tra giá dịch vụ và hoàn tất thanh toán trước khi đến khám.</div></div><Link to="/patient/payments" className="btn bg-white border border-[#ecd89f] text-[#7b5d00]">Xem thanh toán</Link></div></section>}
    <section className="card rounded-3xl bg-white mt-7 p-6"><div className="flex justify-between items-center mb-4"><div><div className="text-xl font-extrabold text-[#183c63]">Lịch sắp tới</div><div className="text-sm text-[#7892aa]">Các cuộc hẹn gần nhất của bạn</div></div><Link to="/patient/appointments" className="btn btn-soft text-sm">Xem tất cả <ChevronRight size={16}/></Link></div>{upcoming.length?<div className="space-y-3">{upcoming.map(a=><AppointmentCard key={a.id} a={a}/>)}</div>:<Empty text="Bạn chưa có lịch khám sắp tới."/>}</section>
  </div>
}

export function Booking(){
  const [specs,setSpecs]=useState([]),[docs,setDocs]=useState([]),[services,setServices]=useState([]),[sid,setSid]=useState(''),[doctor,setDoctor]=useState(null),[service,setService]=useState(null),[date,setDate]=useState(''),[slots,setSlots]=useState([]),[form,setForm]=useState({start_time:'',reason:''}),[paymentMethod,setPaymentMethod]=useState('OFFLINE'),[msg,setMsg]=useState(null),[loading,setLoading]=useState(false);
  const {user}=useAuth(); const nav=useNavigate();
  useEffect(()=>{masterApi.specialties().then(r=>setSpecs(r.data)).catch(e=>setMsg({ok:false,text:getApiErrorMessage(e,'Không tải được chuyên khoa')}))},[]);
  useEffect(()=>{if(!sid){setDocs([]);setServices([]);setDoctor(null);setService(null);setSlots([]);return;} Promise.all([masterApi.doctors(sid),masterApi.services(sid)]).then(([a,b])=>{setDocs(a.data);setServices(b.data);setDoctor(null);setService(null);setSlots([]);setForm(x=>({...x,start_time:''}))}).catch(()=>{setDocs([]);setServices([])})},[sid]);
  useEffect(()=>{if(doctor&&date)bookingApi.slots(doctor.id,date).then(r=>setSlots(r.data)).catch(()=>setSlots([]));else setSlots([])},[doctor,date]);
  const submit=async e=>{e.preventDefault();setLoading(true);setMsg(null);try{const r=await bookingApi.create({doctor_id:doctor.id,service_id:service.id,appointment_date:date,start_time:form.start_time,reason:form.reason,payment_method:paymentMethod});setMsg({ok:true,text:'Đặt lịch thành công.'});setTimeout(()=>nav(paymentMethod==='QR'?`/patient/payment/${r.data.id}`:'/patient/appointments'),350)}catch(e){setMsg({ok:false,text:getApiErrorMessage(e,'Không thể đặt lịch')})}finally{setLoading(false)}};
  return <div><Title title="Đặt lịch khám" text="Chọn chuyên khoa, bác sĩ, dịch vụ, thời gian và phương thức thanh toán."/><div className="grid xl:grid-cols-[1fr_380px] gap-6"><section className="card rounded-3xl bg-white p-6">
    <Step n="1" title="Chọn chuyên khoa"/><div className="grid md:grid-cols-3 gap-3 mt-4">{specs.map(s=><button type="button" key={s.id} onClick={()=>setSid(String(s.id))} className={`text-left rounded-2xl border p-4 transition ${String(s.id)===sid?'border-[#6daef5] bg-[#edf6ff] shadow-sm':'border-[#dfebf6] hover:bg-[#f8fbff]'}`}><div className="font-bold text-[#2c557b]">{s.name}</div><div className="text-xs text-[#7a94ac] mt-1 line-clamp-2">{s.description}</div></button>)}</div>
    <Step n="2" title="Chọn bác sĩ"/><div className="grid md:grid-cols-2 gap-3 mt-4">{docs.map(d=><button type="button" key={d.id} onClick={()=>setDoctor(d)} className={`text-left rounded-2xl border p-4 transition ${doctor?.id===d.id?'border-[#6daef5] bg-[#edf6ff] shadow-sm':'border-[#dfebf6] hover:bg-[#f8fbff]'}`}><div className="flex items-start gap-3"><div className="h-10 w-10 rounded-xl bg-[#eaf4ff] text-[#2f80ed] grid place-items-center"><Stethoscope size={19}/></div><div className="min-w-0"><div className="font-bold text-[#2c557b]">{d.full_name}</div><div className="text-xs text-[#7a94ac] mt-1">{d.specialty_name||'Chuyên khoa'} · Phòng {d.room}</div><div className="text-xs text-[#7a94ac] mt-1 line-clamp-2">{d.bio}</div></div></div></button>)}{sid&&!docs.length&&<Empty text="Chưa có bác sĩ phù hợp với chuyên khoa này."/>}</div>
    <Step n="3" title="Chọn dịch vụ & giá niêm yết"/><div className="grid md:grid-cols-2 gap-3 mt-4">{services.map(x=><button type="button" key={x.id} onClick={()=>setService(x)} className={`text-left rounded-2xl border p-4 transition ${service?.id===x.id?'border-[#6daef5] bg-[#edf6ff] shadow-sm':'border-[#dfebf6] hover:bg-[#f8fbff]'}`}><div className="flex justify-between gap-3"><div><div className="font-bold text-[#2c557b]">{x.name}</div><div className="text-xs text-[#7a94ac] mt-1">{x.description}</div></div><div className="font-black text-[#2f80ed] whitespace-nowrap">{money(x.price)}</div></div></button>)}{sid&&!services.length&&<Empty text="Chưa có dịch vụ cho chuyên khoa này."/>}</div>
    <Step n="4" title="Chọn ngày & giờ"/><div className="grid md:grid-cols-2 gap-4 mt-4"><label><div className="label">Ngày khám</div><input className="input" type="date" min={today()} value={date} onChange={e=>{setDate(e.target.value);setForm(x=>({...x,start_time:''}))}}/></label><div><div className="label">Khung giờ còn trống</div><div className="grid grid-cols-4 gap-2">{slots.map(x=><button type="button" key={x.start_time} onClick={()=>setForm({...form,start_time:x.start_time})} className={`rounded-xl border py-2 text-sm font-bold ${form.start_time===x.start_time?'border-[#2f80ed] bg-[#eaf4ff] text-[#2f80ed]':'border-[#dcecff] text-[#567894] hover:bg-[#f7fbff]'}`}>{x.start_time}</button>)}{date&&doctor&&!slots.length&&<div className="col-span-4 text-sm text-[#849bb0]">Ngày này không có khung giờ trống hoặc bác sĩ nghỉ.</div>}</div></div></div>
    <Step n="5" title="Phương thức thanh toán"/><div className="grid md:grid-cols-2 gap-3 mt-4"><button type="button" onClick={()=>setPaymentMethod('OFFLINE')} className={`rounded-2xl border p-4 text-left ${paymentMethod==='OFFLINE'?'border-[#6daef5] bg-[#edf6ff]':'border-[#dfebf6]'}`}><div className="flex gap-3"><CreditCard className="text-[#2f80ed]"/><div><div className="font-bold text-[#315b83]">Thanh toán tại cơ sở</div><div className="text-xs text-[#7a94ac] mt-1">Thanh toán tại quầy khi đến phòng khám.</div></div></div></button><button type="button" onClick={()=>setPaymentMethod('QR')} className={`rounded-2xl border p-4 text-left ${paymentMethod==='QR'?'border-[#6daef5] bg-[#edf6ff]':'border-[#dfebf6]'}`}><div className="flex gap-3"><QrCode className="text-[#2f80ed]"/><div><div className="font-bold text-[#315b83]">Thanh toán bằng QR</div><div className="text-xs text-[#7a94ac] mt-1">Hiển thị mã QR theo đúng giá niêm yết.</div></div></div></button></div>
    <Step n="6" title="Lý do khám & xác nhận"/><form onSubmit={submit} className="mt-4"><textarea className="input min-h-28" required minLength={3} placeholder="Mô tả ngắn lý do khám…" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/>{msg&&<div className={`mt-3 rounded-xl p-3 text-sm flex items-center gap-2 ${msg.ok?'bg-[#eaf8ef] text-[#16733b]':'bg-[#fff0ef] text-[#b42318]'}`}>{msg.ok?<CheckCircle2 size={16}/>:<AlertCircle size={16}/>} {msg.text}</div>}<button disabled={loading||!doctor||!service||!date||!form.start_time} className="btn btn-primary mt-4">{loading?'Đang xử lý…':paymentMethod==='QR'?'Xác nhận & thanh toán QR':'Xác nhận đặt lịch'}</button></form></section>
    <aside className="card rounded-3xl bg-white p-6 h-fit"><div className="font-extrabold text-[#183c63]">Tóm tắt đặt lịch</div><div className="mt-5 space-y-4 text-sm"><Summary label="Bệnh nhân" value={user?.full_name}/><Summary label="Số điện thoại" value={user?.phone||'Chưa cập nhật'}/><Summary label="Bác sĩ" value={doctor?.full_name||'Chưa chọn'}/><Summary label="Dịch vụ" value={service?.name||'Chưa chọn'}/><Summary label="Giá niêm yết" value={service?money(service.price):'Chưa chọn'}/><Summary label="Ngày" value={date||'Chưa chọn'}/><Summary label="Giờ" value={form.start_time||'Chưa chọn'}/><Summary label="Thanh toán" value={paymentMethod==='QR'?'QR':'Tại cơ sở'}/></div><div className="mt-5 rounded-2xl bg-[#f7fbff] p-4 text-xs text-[#6c88a3]">Giá hiển thị là <b>giá niêm yết mẫu của MedSchedule</b> phục vụ đồ án; không đại diện bảng giá của cơ sở y tế thực tế. QR thanh toán hiện là mô phỏng.</div></aside>
  </div></div>
}

export function MyAppointments(){
  const [apps,setApps]=useState([]),[expanded,setExpanded]=useState(null),[res,setRes]=useState(null),[slots,setSlots]=useState([]),[msg,setMsg]=useState(''),[cancelling,setCancelling]=useState(null); const nav=useNavigate();
  const load=()=>bookingApi.mine().then(r=>setApps(r.data)); useEffect(load,[]);
  const cancel=async id=>{if(cancelling===id||!confirm('Bạn chắc chắn muốn hủy lịch này?'))return;setCancelling(id);setMsg('');try{const r=await bookingApi.cancel(id);setMsg(r.data.refund_pending?'Đã hủy lịch. Khoản đã thanh toán đang chờ nhân viên xác nhận hoàn tiền.':r.data.refund_message||'Đã hủy lịch khám.');await load()}catch(e){setMsg(getApiErrorMessage(e,'Không thể hủy lịch'))}finally{setCancelling(null)}};
  const startReschedule=async a=>{setExpanded(a.id);setRes({id:a.id,date:a.appointment_date,start_time:''});try{const r=await bookingApi.slots(a.doctor_id,a.appointment_date);setSlots(r.data)}catch{setSlots([])}};
  const changeDate=async date=>{setRes(x=>({...x,date,start_time:''}));try{const r=await bookingApi.slots(apps.find(a=>a.id===res.id)?.doctor_id,date);setSlots(r.data)}catch{setSlots([])}};
  const saveReschedule=async()=>{try{await bookingApi.reschedule(res.id,{appointment_date:res.date,start_time:res.start_time});setMsg('Đã đổi lịch khám.');setRes(null);setExpanded(null);load()}catch(e){setMsg(getApiErrorMessage(e,'Không thể đổi lịch'))}};
  return <div><Title title="Lịch khám của tôi" text="Theo dõi lịch, thanh toán, tiếp nhận và kết quả khám."/><div className="mb-5 rounded-2xl bg-[#f7fbff] border border-[#dcecff] p-4 text-sm text-[#5f7d99]">Nếu lịch đã thanh toán rồi bị hủy hoặc không đến khám, khoản tiền sẽ chuyển sang <b>Chờ hoàn tiền</b>. Nhân viên tiếp nhận sẽ kiểm tra thông tin và xác nhận hoàn tiền.</div><div className="space-y-4">{apps.map(a=><div key={a.id} className="card rounded-3xl bg-white p-5"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div className="min-w-0"><div className="flex items-center gap-2"><span className="font-black text-[#264f75] text-lg">{a.doctor_name}</span><span className="badge bg-[#f1f7ff] text-[#5a7897]">{visitLabel(a.visit_type)}</span></div><div className="text-sm text-[#7d96ad] mt-1">Mã lịch <b>{appointmentCode(a.id)}</b> · {a.specialty_name||'Khám tổng quát'} · {a.appointment_date} · {a.start_time}</div><div className="text-sm text-[#7d96ad] mt-1 flex gap-4 flex-wrap"><span><Phone size={13} className="inline mr-1"/>{a.patient_phone||'Chưa có SĐT'}</span><span><ReceiptText size={13} className="inline mr-1"/>{a.service_name||'Dịch vụ'}</span><span className="font-bold text-[#2f80ed]">{a.service_price?money(a.service_price):'Chưa có giá'}</span></div></div><div className="flex items-center gap-2 flex-wrap"><span className={`badge status-${a.status.toLowerCase()}`}>{statusLabel(a.status)}</span><span className={`badge ${a.payment_status==='PAID'?'bg-[#eaf8ef] text-[#16733b]':a.payment_status==='REFUND_PENDING'?'bg-[#fff6df] text-[#8b6200]':'bg-[#eef6ff] text-[#2f70b3]'}`}>Thanh toán: {paymentLabel(a.payment_status)}</span><button className="btn btn-soft text-sm" onClick={()=>setExpanded(expanded===a.id?null:a.id)}>Chi tiết</button>{a.payment_status==='PENDING'&&<button className="btn btn-primary text-sm" onClick={()=>nav(`/patient/payment/${a.id}`)}>Thanh toán</button>}{a.status==='CONFIRMED'&&<><button className="btn btn-outline text-sm" onClick={()=>startReschedule(a)}>Đổi lịch</button><button disabled={cancelling===a.id} className="btn btn-danger text-sm disabled:opacity-50" onClick={()=>cancel(a.id)}>{cancelling===a.id?'Đang hủy…':'Hủy lịch'}</button></>}</div></div>
      {expanded===a.id&&<div className="mt-4 border-t border-[#e5eff8] pt-4"><div className="grid md:grid-cols-2 gap-4"><InfoLine label="Lý do khám" value={a.reason}/><InfoLine label="Dịch vụ & giá" value={`${a.service_name||'—'} · ${a.service_price?money(a.service_price):'—'}`}/><InfoLine label="Bác sĩ" value={a.doctor_name}/><InfoLine label="Thanh toán" value={`${paymentLabel(a.payment_status)}${a.payment_reference?` · ${a.payment_reference}`:''}`}/></div>
      {a.status==='CANCELLED'&&a.payment_status==='REFUND_PENDING'&&<div className="mt-4 rounded-2xl bg-[#fff7dd] border border-[#f0dfaa] p-4 text-sm text-[#805f00]"><div className="font-extrabold">Đang chờ hoàn tiền</div><div className="mt-1">Lịch đã hủy. Khoản thanh toán <b>{money(a.service_price)}</b> đang chờ nhân viên tiếp nhận xác nhận hoàn tiền.</div><div className="mt-1">Mã giao dịch: <b>{a.payment_reference||'—'}</b></div></div>}{a.status==='CANCELLED'&&a.payment_status==='REFUNDED'&&<div className="mt-4 rounded-2xl bg-[#eaf8ef] p-4 text-sm text-[#16733b]"><div className="font-extrabold">Đã hoàn tiền</div><div className="mt-1">Khoản thanh toán đã được nhân viên xác nhận hoàn tiền.</div></div>}{a.status==='COMPLETED'&&<div className="mt-4 rounded-2xl bg-[#f7fbff] p-4"><div className="font-extrabold text-[#2a547a] flex items-center gap-2"><ClipboardCheck size={18}/>Kết quả khám</div><div className="grid md:grid-cols-3 gap-3 mt-3"><InfoLine label="Chẩn đoán" value={a.diagnosis||'—'}/><InfoLine label="Ghi chú" value={a.notes||'—'}/><InfoLine label="Đơn thuốc" value={a.prescription||'—'}/></div></div>}
      {res?.id===a.id&&a.status==='CONFIRMED'&&<div className="mt-4 rounded-2xl bg-[#f7fbff] p-4"><div className="font-bold text-[#315b83]">Chọn lịch mới</div><div className="grid md:grid-cols-2 gap-3 mt-3"><input className="input" type="date" min={today()} value={res.date} onChange={e=>changeDate(e.target.value)}/><div className="grid grid-cols-4 gap-2">{slots.map(x=><button type="button" key={x.start_time} className={`rounded-xl border py-2 text-sm font-bold ${res.start_time===x.start_time?'border-[#2f80ed] bg-[#eaf4ff] text-[#2f80ed]':'border-[#dcecff] text-[#567894]'}`} onClick={()=>setRes({...res,start_time:x.start_time})}>{x.start_time}</button>)}</div></div><div className="flex gap-2 mt-3"><button disabled={!res.date||!res.start_time} className="btn btn-primary" onClick={saveReschedule}>Lưu lịch mới</button><button className="btn btn-outline" onClick={()=>setRes(null)}>Đóng</button></div></div>}</div>}</div>)}{msg&&<div className="rounded-xl bg-[#edf6ff] text-[#2f80ed] p-3 text-sm">{msg}</div>}{!apps.length&&<Empty text="Bạn chưa có lịch khám."/>}</div></div>
}

export function Payments(){
  const [apps,setApps]=useState([]); const nav=useNavigate(); useEffect(()=>{bookingApi.mine().then(r=>setApps(r.data)).catch(()=>{})},[]); const rows=apps.filter(a=>a.payment_id); return <div><Title title="Thanh toán" text="Theo dõi giá dịch vụ niêm yết, trạng thái thanh toán và hoàn tiền."/><div className="grid md:grid-cols-3 gap-4 mb-6"><InfoCard icon={WalletCards} label="Chưa thanh toán" value={rows.filter(a=>['UNPAID','PENDING'].includes(a.payment_status)).length}/><InfoCard icon={CheckCircle2} label="Đã thanh toán" value={rows.filter(a=>a.payment_status==='PAID').length}/><InfoCard icon={ReceiptText} label="Chờ hoàn tiền" value={rows.filter(a=>a.payment_status==='REFUND_PENDING').length}/></div><div className="space-y-3">{rows.map(a=><div key={a.id} className="card rounded-2xl bg-white p-5 flex flex-col md:flex-row md:items-center justify-between gap-4"><div><div className="font-extrabold text-[#2a5278]">{a.service_name||'Dịch vụ khám'}</div><div className="text-sm text-[#7893ab] mt-1">{appointmentCode(a.id)} · {a.appointment_date} · {a.start_time}</div><div className="text-sm text-[#315b83] mt-2 font-bold">{money(a.service_price)}</div></div><div className="flex items-center gap-2 flex-wrap"><span className="badge bg-[#f1f7ff] text-[#5d7c98]">{paymentLabel(a.payment_status)}</span>{a.payment_status==='PENDING'&&<button className="btn btn-primary" onClick={()=>nav(`/patient/payment/${a.id}`)}><QrCode size={16}/>Thanh toán</button>}</div></div>)}{!rows.length&&<Empty text="Chưa có giao dịch thanh toán."/>}</div></div>
}

export function PaymentPage(){
  const {appointmentId}=useParams(); const [p,setP]=useState(null),[msg,setMsg]=useState('');
  const load=()=>paymentApi.get(appointmentId).then(r=>setP(r.data)).catch(e=>setMsg(getApiErrorMessage(e,'Không tải được thanh toán'))); useEffect(load,[appointmentId]);
  const confirm=async()=>{try{const r=await paymentApi.confirmDemo(appointmentId);setP(r.data);setMsg('Thanh toán mô phỏng thành công.')}catch(e){setMsg(getApiErrorMessage(e,'Không thể xác nhận thanh toán'))}};
  const later=async()=>{try{const r=await paymentApi.payLater(appointmentId);setP(r.data);setMsg('Đã chuyển sang thanh toán tại cơ sở.')}catch(e){setMsg(getApiErrorMessage(e,'Không thể thay đổi phương thức thanh toán'))}};
  return <div><Title title="Thanh toán lịch khám" text="Kiểm tra giá niêm yết và hoàn tất thanh toán cho lịch của bạn."/>{p?<div className="grid lg:grid-cols-[1fr_420px] gap-6"><section className="card rounded-3xl bg-white p-6"><div className="flex items-center gap-3"><div className="h-12 w-12 rounded-2xl bg-[#eaf4ff] text-[#2f80ed] grid place-items-center"><WalletCards/></div><div><div className="font-black text-[#234d73] text-xl">{p.service_name}</div><div className="text-sm text-[#7a94ac]">Mã giao dịch: {p.reference}</div></div></div><div className="grid grid-cols-2 gap-4 mt-6"><InfoLine label="Giá niêm yết" value={money(p.amount)}/><InfoLine label="Phương thức" value={p.method==='QR'?'Thanh toán QR':'Thanh toán tại cơ sở'}/><InfoLine label="Trạng thái" value={paymentLabel(p.status)}/><InfoLine label="Mã lịch" value={appointmentCode(Number(appointmentId))}/></div>{p.status==='PENDING'&&<><div className="mt-6 rounded-2xl bg-[#f7fbff] p-4 text-sm text-[#5f7d99]">Quét mã QR bên phải để thực hiện thanh toán. Đây là <b>QR mô phỏng phục vụ đồ án</b>, không kết nối ngân hàng thật.</div><div className="flex gap-2 mt-4"><button className="btn btn-primary" onClick={confirm}><CheckCircle2 size={16}/>Tôi đã thanh toán</button><button className="btn btn-outline" onClick={later}>Thanh toán tại cơ sở</button></div></>}{p.status==='PAID'&&<div className="mt-6 rounded-2xl bg-[#eaf8ef] text-[#16733b] p-4 font-bold">Thanh toán thành công.</div>}{p.status==='REFUND_PENDING'&&<div className="mt-6 rounded-2xl bg-[#fff7dd] text-[#805f00] p-4">Khoản thanh toán đang chờ nhân viên xử lý hoàn tiền do lịch đã hủy hoặc không đến khám.</div>}{p.status==='UNPAID'&&<div className="mt-6 rounded-2xl bg-[#edf6ff] text-[#2f70b3] p-4">Bạn sẽ thanh toán tại phòng khám khi đến.</div>}{msg&&<div className="mt-4 rounded-xl bg-[#edf6ff] text-[#2f80ed] p-3 text-sm">{msg}</div>}</section><aside className="card rounded-3xl bg-white p-6 text-center">{p.method==='QR'&&p.qr_image?<><div className="font-extrabold text-[#234d73]">Mã QR thanh toán</div><img src={p.qr_image} alt="Mã QR thanh toán" className="mx-auto mt-5 w-72 h-72 rounded-2xl border border-[#dcecff] p-3"/><div className="mt-4 text-2xl font-black text-[#24547d]">{money(p.amount)}</div><div className="text-xs text-[#7d96ad] mt-2 break-all">{p.reference}</div></>:<div className="py-14 text-[#7892aa]">Không có mã QR cho phương thức này.</div>}</aside></div>:<div className="card p-8 bg-white">Đang tải thông tin thanh toán…{msg&&<div className="mt-4 text-sm text-[#b42318]">{msg}</div>}</div>}</div>
}

export function Profile(){const {user}=useAuth();const [f,setF]=useState({date_of_birth:'',gender:'',address:'',emergency_contact:''}),[pwd,setPwd]=useState({current_password:'',new_password:''}),[msg,setMsg]=useState('');useEffect(()=>{if(user?.patient_id)masterApi.profile(user.patient_id).then(r=>setF({date_of_birth:r.data.date_of_birth||'',gender:r.data.gender||'',address:r.data.address||'',emergency_contact:r.data.emergency_contact||''})).catch(()=>{})},[user]);const save=async e=>{e.preventDefault();try{await masterApi.updateProfile(user.patient_id,f);setMsg('Đã lưu hồ sơ.')}catch(e){setMsg(getApiErrorMessage(e,'Không thể lưu hồ sơ'))}};const changePassword=async e=>{e.preventDefault();try{await authApi.changePassword(pwd);setPwd({current_password:'',new_password:''});setMsg('Đổi mật khẩu thành công.')}catch(e){setMsg(getApiErrorMessage(e,'Không thể đổi mật khẩu'))}};return <div><Title title="Hồ sơ cá nhân" text="Thông tin dùng để tra cứu và liên hệ khi tiếp nhận."/><div className="grid xl:grid-cols-2 gap-6"><div className="card rounded-3xl bg-white p-6"><div className="flex items-center gap-4"><div className="h-14 w-14 rounded-2xl bg-[#eaf4ff] text-[#2f80ed] grid place-items-center"><UserRound/></div><div><div className="text-xl font-extrabold text-[#244e74]">{user?.full_name}</div><div className="text-sm text-[#7992a8]">{user?.email}</div><div className="text-sm text-[#7992a8]">{user?.phone||'Chưa cập nhật SĐT'}</div></div></div><form onSubmit={save} className="grid md:grid-cols-2 gap-4 mt-6"><Field label="Ngày sinh" value={f.date_of_birth} onChange={v=>setF({...f,date_of_birth:v})}/><Field label="Giới tính" value={f.gender} onChange={v=>setF({...f,gender:v})}/><Field label="Địa chỉ" value={f.address} onChange={v=>setF({...f,address:v})}/><Field label="Liên hệ khẩn cấp" value={f.emergency_contact} onChange={v=>setF({...f,emergency_contact:v})}/><div className="md:col-span-2"><button className="btn btn-primary">Lưu thay đổi</button></div></form></div><div className="card rounded-3xl bg-white p-6 h-fit"><div className="font-extrabold text-[#234d73]">Đổi mật khẩu</div><form onSubmit={changePassword} className="space-y-4 mt-4"><Field label="Mật khẩu hiện tại" type="password" value={pwd.current_password} onChange={v=>setPwd({...pwd,current_password:v})}/><Field label="Mật khẩu mới" type="password" value={pwd.new_password} onChange={v=>setPwd({...pwd,new_password:v})}/><button className="btn btn-primary">Đổi mật khẩu</button></form>{msg&&<div className="mt-4 rounded-xl bg-[#edf6ff] text-[#2f80ed] p-3 text-sm">{msg}</div>}</div></div></div>}

function Field({label,type='text',value,onChange}){return <label><div className="label">{label}</div><input className="input" type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Summary({label,value}){return <div><div className="text-[11px] font-bold uppercase tracking-wider text-[#88a1b8]">{label}</div><div className="mt-1 font-bold text-[#315b83]">{value||'—'}</div></div>}
function InfoLine({label,value}){return <div><div className="text-xs font-bold uppercase tracking-wider text-[#8ca4b9]">{label}</div><div className="mt-1 text-sm font-semibold text-[#355b7e] break-words">{value||'—'}</div></div>}
function AppointmentCard({a}){return <div className="rounded-2xl border border-[#dfebf5] p-4 flex flex-col md:flex-row md:items-center justify-between gap-3"><div><div className="font-bold text-[#315a81]">{a.doctor_name}</div><div className="text-sm text-[#7892aa] mt-1">{appointmentCode(a.id)} · {a.appointment_date} · {a.start_time}</div><div className="text-xs text-[#7d96ad] mt-1">{a.service_name||'Dịch vụ khám'} · {a.service_price?money(a.service_price):'—'}</div></div><span className={`badge status-${a.status.toLowerCase()}`}>{statusLabel(a.status)}</span></div>}
function Hero({title,text,action,to,icon:Icon}){return <div className="rounded-3xl p-7 md:p-9 bg-gradient-to-r from-[#2f80ed] to-[#6daef5] text-white shadow-[0_20px_50px_rgba(47,128,237,.25)]"><div className="max-w-2xl"><div className="text-3xl md:text-4xl font-black">{title}</div><div className="mt-2 text-white/85 text-lg">{text}</div><Link to={to} className="mt-6 btn bg-white text-[#2f80ed] hover:bg-white/95"><Icon size={18}/>{action}</Link></div></div>}
function InfoCard({icon:Icon,label,value}){return <div className="card rounded-2xl bg-white p-5 flex items-center gap-4"><div className="h-11 w-11 rounded-xl bg-[#edf6ff] text-[#2f80ed] grid place-items-center"><Icon size={21}/></div><div><div className="text-xs font-bold uppercase tracking-[.12em] text-[#86a2bb]">{label}</div><div className="text-xl font-black text-[#244c72] mt-1">{value}</div></div></div>}
function Step({n,title}){return <div className="mt-7 flex items-center gap-3"><div className="h-8 w-8 rounded-lg bg-[#eaf4ff] text-[#2f80ed] grid place-items-center font-black text-sm">{n}</div><div className="font-extrabold text-[#234c72]">{title}</div></div>}
function Title({title,text}){return <div className="mb-6"><div className="text-3xl font-black text-[#17395f]">{title}</div><div className="mt-1 text-[#7892aa]">{text}</div></div>}
function Empty({text}){return <div className="rounded-2xl border border-dashed border-[#cfe1f3] p-10 text-center text-[#7892aa]">{text}</div>}
